export enum GlobalActions {
    SAVED_CLIENT_ID = "SAVED_CLIENT_ID",
    TAKE_CONTROL_SUCCESS = "TAKE_CONTROL_SUCCESS",
    EXITED_RC_MODE = "EXITED_RC_MODE",
    CLOSED_DETAILS = "CLOSED_DETAILS",
    CLICKED_NODE = "CLICKED_NODE",
    CLICKED_HUB_ACCORDION = "CLICKED_HUB_ACCORDION",
    CLICKED_BOT_ACCORDION = "CLICKED_BOT_ACCORDION",
}
