# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jaiabot/messages/lora_test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2
from jaiabot.messages import feather_pb2 as jaiabot_dot_messages_dot_feather__pb2
from goby.middleware.protobuf import gpsd_pb2 as goby_dot_middleware_dot_protobuf_dot_gpsd__pb2
from jaiabot.messages import geographic_coordinate_pb2 as jaiabot_dot_messages_dot_geographic__coordinate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jaiabot/messages/lora_test.proto',
  package='jaiabot.protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n jaiabot/messages/lora_test.proto\x12\x10jaiabot.protobuf\x1a\x1c\x64\x63\x63l/option_extensions.proto\x1a\x1ejaiabot/messages/feather.proto\x1a#goby/middleware/protobuf/gpsd.proto\x1a,jaiabot/messages/geographic_coordinate.proto\"\xad\x01\n\x0cLoRaTestData\x12-\n\x04time\x18\x01 \x02(\x04\x42\x1f\xa2?\x1c\n\ndccl.time2\xf2\x01\r\x12\x04time2\x05micro\x12$\n\x05index\x18\x02 \x02(\rB\x15\xa2?\x12)\x00\x00\x00\x00\x00\x00\x00\x00\x31\x00\x00\x00\x00\x00@\x8f@\x12\x38\n\x08location\x18\n \x02(\x0b\x32&.jaiabot.protobuf.GeographicCoordinate:\x0e\xa2?\x0b\x08|\x10@(\x03\xf2\x01\x02si\"\x86\x03\n\nLoRaReport\x12-\n\x04time\x18\x01 \x02(\x04\x42\x1f\xa2?\x1c\n\ndccl.time2\xf2\x01\r\x12\x04time2\x05micro\x12\x33\n\x06status\x18\n \x02(\x0e\x32#.jaiabot.protobuf.LoRaReport.Status\x12\x32\n\x0b\x66\x65\x61ther_msg\x18\x14 \x01(\x0b\x32\x1d.jaiabot.protobuf.LoRaMessage\x12\x31\n\ttest_data\x18\x1e \x01(\x0b\x32\x1e.jaiabot.protobuf.LoRaTestData\x12\x44\n\x07gps_tpv\x18( \x01(\x0b\x32\x33.goby.middleware.protobuf.gpsd.TimePositionVelocity\x12\x18\n\x05range\x18\x32 \x01(\x01\x42\t\xa2?\x06\xf2\x01\x03\n\x01L\x12\x16\n\x0epacket_success\x18< \x01(\x01\"+\n\x06Status\x12\x12\n\x0eGOOD_RECEPTION\x10\x01\x12\r\n\tNO_PACKET\x10\x02:\x08\xa2?\x05\xf2\x01\x02si')
  ,
  dependencies=[dccl_dot_option__extensions__pb2.DESCRIPTOR,jaiabot_dot_messages_dot_feather__pb2.DESCRIPTOR,goby_dot_middleware_dot_protobuf_dot_gpsd__pb2.DESCRIPTOR,jaiabot_dot_messages_dot_geographic__coordinate__pb2.DESCRIPTOR,])



_LORAREPORT_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='jaiabot.protobuf.LoRaReport.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GOOD_RECEPTION', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_PACKET', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=713,
  serialized_end=756,
)
_sym_db.RegisterEnumDescriptor(_LORAREPORT_STATUS)


_LORATESTDATA = _descriptor.Descriptor(
  name='LoRaTestData',
  full_name='jaiabot.protobuf.LoRaTestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='jaiabot.protobuf.LoRaTestData.time', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\242?\034\n\ndccl.time2\362\001\r\022\004time2\005micro'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='jaiabot.protobuf.LoRaTestData.index', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\242?\022)\000\000\000\000\000\000\000\0001\000\000\000\000\000@\217@'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='jaiabot.protobuf.LoRaTestData.location', index=2,
      number=10, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\242?\013\010|\020@(\003\362\001\002si'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=373,
)


_LORAREPORT = _descriptor.Descriptor(
  name='LoRaReport',
  full_name='jaiabot.protobuf.LoRaReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='jaiabot.protobuf.LoRaReport.time', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\242?\034\n\ndccl.time2\362\001\r\022\004time2\005micro'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='jaiabot.protobuf.LoRaReport.status', index=1,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feather_msg', full_name='jaiabot.protobuf.LoRaReport.feather_msg', index=2,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='test_data', full_name='jaiabot.protobuf.LoRaReport.test_data', index=3,
      number=30, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gps_tpv', full_name='jaiabot.protobuf.LoRaReport.gps_tpv', index=4,
      number=40, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='range', full_name='jaiabot.protobuf.LoRaReport.range', index=5,
      number=50, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\242?\006\362\001\003\n\001L'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packet_success', full_name='jaiabot.protobuf.LoRaReport.packet_success', index=6,
      number=60, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LORAREPORT_STATUS,
  ],
  serialized_options=_b('\242?\005\362\001\002si'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=766,
)

_LORATESTDATA.fields_by_name['location'].message_type = jaiabot_dot_messages_dot_geographic__coordinate__pb2._GEOGRAPHICCOORDINATE
_LORAREPORT.fields_by_name['status'].enum_type = _LORAREPORT_STATUS
_LORAREPORT.fields_by_name['feather_msg'].message_type = jaiabot_dot_messages_dot_feather__pb2._LORAMESSAGE
_LORAREPORT.fields_by_name['test_data'].message_type = _LORATESTDATA
_LORAREPORT.fields_by_name['gps_tpv'].message_type = goby_dot_middleware_dot_protobuf_dot_gpsd__pb2._TIMEPOSITIONVELOCITY
_LORAREPORT_STATUS.containing_type = _LORAREPORT
DESCRIPTOR.message_types_by_name['LoRaTestData'] = _LORATESTDATA
DESCRIPTOR.message_types_by_name['LoRaReport'] = _LORAREPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoRaTestData = _reflection.GeneratedProtocolMessageType('LoRaTestData', (_message.Message,), dict(
  DESCRIPTOR = _LORATESTDATA,
  __module__ = 'jaiabot.messages.lora_test_pb2'
  # @@protoc_insertion_point(class_scope:jaiabot.protobuf.LoRaTestData)
  ))
_sym_db.RegisterMessage(LoRaTestData)

LoRaReport = _reflection.GeneratedProtocolMessageType('LoRaReport', (_message.Message,), dict(
  DESCRIPTOR = _LORAREPORT,
  __module__ = 'jaiabot.messages.lora_test_pb2'
  # @@protoc_insertion_point(class_scope:jaiabot.protobuf.LoRaReport)
  ))
_sym_db.RegisterMessage(LoRaReport)


_LORATESTDATA.fields_by_name['time']._options = None
_LORATESTDATA.fields_by_name['index']._options = None
_LORATESTDATA._options = None
_LORAREPORT.fields_by_name['time']._options = None
_LORAREPORT.fields_by_name['range']._options = None
_LORAREPORT._options = None
# @@protoc_insertion_point(module_scope)
