import { TaskPacket } from './JAIAProtobuf';
import VectorLayer from 'ol/layer/Vector';
import VectorSource from 'ol/source/Vector';
import { Geometry, Point } from 'ol/geom';
import { Feature } from 'ol';
import { Map } from 'ol';
export declare function createDivePacketFeature(map: Map, task_packet: TaskPacket): Feature<Point>;
export declare function createDriftPacketFeature(map: Map, taskPacket: TaskPacket): Feature<Point>;
export declare function getDivePacketFeature(map: Map, taskPacket: TaskPacket, divePacketLayer: VectorLayer<VectorSource<Geometry>>): Feature<Geometry>;
export declare function getDriftPacketFeature(map: Map, taskPacket: TaskPacket, driftPacketLayer: VectorLayer<VectorSource<Geometry>>): Feature<Geometry>;
