---
- name: Start/Stop VirtualFleet EC2 instances
  hosts: localhost
  gather_facts: yes

  tasks:
    - name: Read cloud.env
      include_tasks: tasks/cloud-read-env.yml
      tags: read
    
    - name: Change instance state
      include_tasks: tasks/cloud-instance-state.yml
      vars: 
        - do_wait: false
