---
- name: Set the DCCL password for the fleet
  hosts: all
  become: yes
  gather_facts: no
  vars:
    allowed_values:
      - generate_new_password
      - copy_hub_password_to_all
      - clear_password
  pre_tasks:
    - name: Check if action is a valid enumeration
      ansible.builtin.assert:
        that:
          - action is defined
          - action in allowed_values
        fail_msg: "Invalid action. Allowed values are: {{ allowed_values | join('; ') }}"
  tasks:
    - block:
        - name: Create new dccl_password
          set_fact:
            generated_password: "{{ lookup('password', '/dev/null', chars=['0123456789abcdef'], length=32) }}"
          delegate_facts: true

        - name: Read and copy hub password
          set_fact:
            dccl_password: "{{ hostvars['localhost']['generated_password']  }}"

      when: action == "generate_new_password"
      delegate_to: localhost
        
    - block:
        - include_tasks: tasks/read-debconf.yml
          
        - name: Read and copy hub password
          set_fact:
            dccl_password: "{{ jaiabot_embedded_dccl_encryption_password }}"

        - name: Check that password is not empty
          fail:
            msg: "Hub password is not set. Use 'generate_new_password' to create."
          when: dccl_password == ''
      when: action == "copy_hub_password_to_all"
      delegate_to: localhost
          

    - name: Clear password
      set_fact:
        dccl_password: ""
      when: action == "clear_password"
      
    - name: Set new dccl_encryption_password
      debconf:
        name: jaiabot_embedded
        question: "jaiabot-embedded/dccl_encryption_password"
        value: "{{ dccl_password }}"
        vtype: "string"

    - name: Reconfigure package
      command: dpkg-reconfigure -f noninteractive jaiabot-embedded

    - name: Restart JaiaBot services
      command: systemctl restart jaiabot
