# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jaiabot/messages/echo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jaiabot/messages/echo.proto',
  package='jaiabot.protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1bjaiabot/messages/echo.proto\x12\x10jaiabot.protobuf\x1a\x1c\x64\x63\x63l/option_extensions.proto\"\xec\x01\n\x0b\x45\x63hoCommand\x12;\n\x04type\x18\x01 \x02(\x0e\x32-.jaiabot.protobuf.EchoCommand.EchoCommandType\"\x9f\x01\n\x0f\x45\x63hoCommandType\x12\r\n\tCMD_START\x10\x00\x12\x0c\n\x08\x43MD_STOP\x10\x01\x12\x0f\n\x0b\x43MD_STORAGE\x10\x02\x12\x0b\n\x07\x43MD_ACK\x10\x03\x12\x0e\n\nCMD_STATUS\x10\x04\x12\n\n\x06\x43MD_CH\x10\x05\x12\x0c\n\x08\x43MD_FREQ\x10\x06\x12\x0c\n\x08\x43MD_TIME\x10\x07\x12\x0b\n\x07\x43MD_VER\x10\x08\x12\x0c\n\x08\x43MD_HELP\x10\t\"D\n\x08\x45\x63hoData\x12\x38\n\necho_state\x18\x01 \x01(\x0e\x32\x1b.jaiabot.protobuf.EchoState:\x07\x42OOTING\"\xa6\x01\n\tEchoIssue\x12:\n\x08solution\x18\x01 \x02(\x0e\x32(.jaiabot.protobuf.EchoIssue.SolutionType\"]\n\x0cSolutionType\x12\x0f\n\x0bREPORT_ECHO\x10\x00\x12\x13\n\x0fRESTART_ECHO_PY\x10\x01\x12\'\n#REBOOT_ECHO_IMU_AND_RESTART_ECHO_PY\x10\x03*\x89\x01\n\tEchoState\x12\x0b\n\x07\x42OOTING\x10\x00\x12\x0b\n\x07OCTOSPI\x10\x01\x12\x0b\n\x07SD_INIT\x10\x02\x12\x0c\n\x08SD_MOUNT\x10\x03\x12\r\n\tSD_CREATE\x10\x04\x12\x0b\n\x07PSSI_EN\x10\x05\x12\t\n\x05READY\x10\x06\x12\t\n\x05START\x10\x07\x12\x08\n\x04STOP\x10\x08\x12\x0b\n\x07RUNNING\x10\t')
  ,
  dependencies=[dccl_dot_option__extensions__pb2.DESCRIPTOR,])

_ECHOSTATE = _descriptor.EnumDescriptor(
  name='EchoState',
  full_name='jaiabot.protobuf.EchoState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BOOTING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OCTOSPI', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SD_INIT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SD_MOUNT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SD_CREATE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PSSI_EN', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='START', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUNNING', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=558,
  serialized_end=695,
)
_sym_db.RegisterEnumDescriptor(_ECHOSTATE)

EchoState = enum_type_wrapper.EnumTypeWrapper(_ECHOSTATE)
BOOTING = 0
OCTOSPI = 1
SD_INIT = 2
SD_MOUNT = 3
SD_CREATE = 4
PSSI_EN = 5
READY = 6
START = 7
STOP = 8
RUNNING = 9


_ECHOCOMMAND_ECHOCOMMANDTYPE = _descriptor.EnumDescriptor(
  name='EchoCommandType',
  full_name='jaiabot.protobuf.EchoCommand.EchoCommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CMD_START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_STOP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_STORAGE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_ACK', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_STATUS', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_CH', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_FREQ', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_TIME', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_VER', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CMD_HELP', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=157,
  serialized_end=316,
)
_sym_db.RegisterEnumDescriptor(_ECHOCOMMAND_ECHOCOMMANDTYPE)

_ECHOISSUE_SOLUTIONTYPE = _descriptor.EnumDescriptor(
  name='SolutionType',
  full_name='jaiabot.protobuf.EchoIssue.SolutionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REPORT_ECHO', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESTART_ECHO_PY', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REBOOT_ECHO_IMU_AND_RESTART_ECHO_PY', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=462,
  serialized_end=555,
)
_sym_db.RegisterEnumDescriptor(_ECHOISSUE_SOLUTIONTYPE)


_ECHOCOMMAND = _descriptor.Descriptor(
  name='EchoCommand',
  full_name='jaiabot.protobuf.EchoCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='jaiabot.protobuf.EchoCommand.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ECHOCOMMAND_ECHOCOMMANDTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=316,
)


_ECHODATA = _descriptor.Descriptor(
  name='EchoData',
  full_name='jaiabot.protobuf.EchoData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='echo_state', full_name='jaiabot.protobuf.EchoData.echo_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=386,
)


_ECHOISSUE = _descriptor.Descriptor(
  name='EchoIssue',
  full_name='jaiabot.protobuf.EchoIssue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='solution', full_name='jaiabot.protobuf.EchoIssue.solution', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ECHOISSUE_SOLUTIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=555,
)

_ECHOCOMMAND.fields_by_name['type'].enum_type = _ECHOCOMMAND_ECHOCOMMANDTYPE
_ECHOCOMMAND_ECHOCOMMANDTYPE.containing_type = _ECHOCOMMAND
_ECHODATA.fields_by_name['echo_state'].enum_type = _ECHOSTATE
_ECHOISSUE.fields_by_name['solution'].enum_type = _ECHOISSUE_SOLUTIONTYPE
_ECHOISSUE_SOLUTIONTYPE.containing_type = _ECHOISSUE
DESCRIPTOR.message_types_by_name['EchoCommand'] = _ECHOCOMMAND
DESCRIPTOR.message_types_by_name['EchoData'] = _ECHODATA
DESCRIPTOR.message_types_by_name['EchoIssue'] = _ECHOISSUE
DESCRIPTOR.enum_types_by_name['EchoState'] = _ECHOSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoCommand = _reflection.GeneratedProtocolMessageType('EchoCommand', (_message.Message,), dict(
  DESCRIPTOR = _ECHOCOMMAND,
  __module__ = 'jaiabot.messages.echo_pb2'
  # @@protoc_insertion_point(class_scope:jaiabot.protobuf.EchoCommand)
  ))
_sym_db.RegisterMessage(EchoCommand)

EchoData = _reflection.GeneratedProtocolMessageType('EchoData', (_message.Message,), dict(
  DESCRIPTOR = _ECHODATA,
  __module__ = 'jaiabot.messages.echo_pb2'
  # @@protoc_insertion_point(class_scope:jaiabot.protobuf.EchoData)
  ))
_sym_db.RegisterMessage(EchoData)

EchoIssue = _reflection.GeneratedProtocolMessageType('EchoIssue', (_message.Message,), dict(
  DESCRIPTOR = _ECHOISSUE,
  __module__ = 'jaiabot.messages.echo_pb2'
  # @@protoc_insertion_point(class_scope:jaiabot.protobuf.EchoIssue)
  ))
_sym_db.RegisterMessage(EchoIssue)


# @@protoc_insertion_point(module_scope)
