# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jaiabot/messages/modem_message_extensions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goby.acomms.protobuf import modem_message_pb2 as goby_dot_acomms_dot_protobuf_dot_modem__message__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jaiabot/messages/modem_message_extensions.proto',
  package='jaiabot.protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n/jaiabot/messages/modem_message_extensions.proto\x12\x10jaiabot.protobuf\x1a(goby/acomms/protobuf/modem_message.proto\"C\n\x07HubInfo\x12\x0e\n\x06hub_id\x18\x01 \x01(\x05\x12\x10\n\x08modem_id\x18\x02 \x01(\x05\x12\x16\n\x07\x63hanged\x18\x03 \x01(\x08:\x05\x66\x61lse\"6\n\x0cTransmission\x12&\n\x03hub\x18\x01 \x01(\x0b\x32\x19.jaiabot.protobuf.HubInfo:^\n\x0ctransmission\x12\'.goby.acomms.protobuf.ModemTransmission\x18\xdc\x0b \x01(\x0b\x32\x1e.jaiabot.protobuf.Transmission')
  ,
  dependencies=[goby_dot_acomms_dot_protobuf_dot_modem__message__pb2.DESCRIPTOR,])


TRANSMISSION_FIELD_NUMBER = 1500
transmission = _descriptor.FieldDescriptor(
  name='transmission', full_name='jaiabot.protobuf.transmission', index=0,
  number=1500, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_HUBINFO = _descriptor.Descriptor(
  name='HubInfo',
  full_name='jaiabot.protobuf.HubInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hub_id', full_name='jaiabot.protobuf.HubInfo.hub_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='modem_id', full_name='jaiabot.protobuf.HubInfo.modem_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='changed', full_name='jaiabot.protobuf.HubInfo.changed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=178,
)


_TRANSMISSION = _descriptor.Descriptor(
  name='Transmission',
  full_name='jaiabot.protobuf.Transmission',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hub', full_name='jaiabot.protobuf.Transmission.hub', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=234,
)

_TRANSMISSION.fields_by_name['hub'].message_type = _HUBINFO
DESCRIPTOR.message_types_by_name['HubInfo'] = _HUBINFO
DESCRIPTOR.message_types_by_name['Transmission'] = _TRANSMISSION
DESCRIPTOR.extensions_by_name['transmission'] = transmission
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HubInfo = _reflection.GeneratedProtocolMessageType('HubInfo', (_message.Message,), dict(
  DESCRIPTOR = _HUBINFO,
  __module__ = 'jaiabot.messages.modem_message_extensions_pb2'
  # @@protoc_insertion_point(class_scope:jaiabot.protobuf.HubInfo)
  ))
_sym_db.RegisterMessage(HubInfo)

Transmission = _reflection.GeneratedProtocolMessageType('Transmission', (_message.Message,), dict(
  DESCRIPTOR = _TRANSMISSION,
  __module__ = 'jaiabot.messages.modem_message_extensions_pb2'
  # @@protoc_insertion_point(class_scope:jaiabot.protobuf.Transmission)
  ))
_sym_db.RegisterMessage(Transmission)

transmission.message_type = _TRANSMISSION
goby_dot_acomms_dot_protobuf_dot_modem__message__pb2.ModemTransmission.RegisterExtension(transmission)

# @@protoc_insertion_point(module_scope)
