#include <Servo.h>
Servo motor_servo;

const int VvCurrent = A3;
const int VccCurrent = A2;
const int VccVoltage = A0;
const int LED1 = A6;
const int LED2 = A5;
const int motor = 3;
const int CTRL_ACTS = 10;
const int FAULT_ACTS = 8;
const int POWER_PIN = A1;
int vccvoltage = 0;
int vcccurrent = 0;
int Vvcurrent = 0;
void setup() {
  // put your setup code here, to run once:
  Serial.begin(19200);
  motor_servo.attach(motor);
  digitalWrite(POWER_PIN, LOW);
  pinMode(CTRL_ACTS, OUTPUT);
  digitalWrite(CTRL_ACTS, LOW);

  pinMode(FAULT_ACTS, INPUT);
  pinMode(VccCurrent, INPUT);
  pinMode(VccVoltage, INPUT);
  pinMode(VvCurrent, INPUT);
  pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  Serial.begin(19200);
  motor_servo.writeMicroseconds(1500);
}

void loop() {
  // put your main code here, to run repeatedly:
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1550);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1600);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1650);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1700);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1750);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1800);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1850);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1900);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1850);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1800);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1750);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1700);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1650);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1600);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1550);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1500);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1450);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1400);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1350);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1300);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1250);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1200);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1150);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1100);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1150);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1200);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1250);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1300);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1350);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1400);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1450);
vccvoltage = analogRead(VccVoltage);
vcccurrent = analogRead(VccCurrent);
Vvcurrent = analogRead(VvCurrent);
Serial.println(vccvoltage);
Serial.println(vcccurrent);
Serial.println(Vvcurrent);
delay(1500);
motor_servo.writeMicroseconds(1500);
}
