import { missionSet } from "../mission_set/mission-set";
import {
    PendingReroute,
    PendingWaypointRemoval,
    PendingWaypointRemovalProposal,
} from "./exclusion-zone-set";
import { detectReroutesWithOverrides, getBlockingZoneIDs } from "../../utils/exclusion-zone-router";

/**
 * Scans all missions for zone crossings and returns reroute proposals.
 * Returns null if no missions are affected.
 */
export function detectMissionReroutes(): PendingReroute | null {
    return detectReroutesWithOverrides(new Map());
}

/**
 * Scans all missions for waypoints that fall inside the safety buffer of any
 * active exclusion zone. Works on clean (bypass-stripped) waypoints so that
 * auto-generated bypass waypoints are never flagged. Returns removal proposals,
 * or null if no missions are affected.
 */
export function detectWaypointRemovals(
    triggeringZoneID?: number,
    removeOffendingZonesOnCancel?: boolean,
): PendingWaypointRemoval | null {
    const proposals: PendingWaypointRemovalProposal[] = [];
    const offendingZoneIDSet = new Set<number>();

    for (const [missionID, mission] of missionSet.getMissions()) {
        const cleanWaypoints = mission.getWaypoints().filter((wp) => !wp.getIsBypass());

        const keepWaypoints = cleanWaypoints.filter((wp) => {
            const loc = wp.getLocation();
            if (!loc) return true;
            const blockingIDs = getBlockingZoneIDs(loc);
            if (blockingIDs.length === 0) return true;
            blockingIDs.forEach((id) => offendingZoneIDSet.add(id));
            return false;
        });

        const removedCount = cleanWaypoints.length - keepWaypoints.length;
        if (removedCount === 0) continue;

        proposals.push({ missionID, newWaypoints: keepWaypoints, removedCount });
    }

    if (proposals.length === 0) return null;

    // Pre-compute reroutes against the post-removal state so both can be shown
    // in a single dialog without a second round-trip through the data model.
    const overrides = new Map(proposals.map((p) => [p.missionID, p.newWaypoints]));
    const followUpReroute = detectReroutesWithOverrides(overrides) ?? undefined;

    const result: PendingWaypointRemoval = {
        proposals,
        totalRemovedCount: proposals.reduce((sum, p) => sum + p.removedCount, 0),
        followUpReroute,
    };

    if (triggeringZoneID !== undefined) {
        result.triggeringZoneID = triggeringZoneID;
    } else if (removeOffendingZonesOnCancel) {
        result.offendingZoneIDs = Array.from(offendingZoneIDSet);
    }

    return result;
}
