- name: Set download URL
  set_fact:
    upgrade_rootfs_url: 'http://{{ hub_ip }}/updates/major_upgrade/{{ major_upgrade_rootfs_version }}.rootfs.tar.gz'
    upgrade_boot_url: 'http://{{ hub_ip }}/updates/major_upgrade/{{ major_upgrade_rootfs_version }}.boot.tar.gz'    

- name: Download the upgrade image boot fs using wget
  get_url:
    url: "{{ upgrade_boot_url }}"
    dest: "{{ upgrade_dir }}"
    checksum: "{{ major_upgrade_bootfs_checksum }}"
    force: true
  environment:
    TMPDIR: "{{ upgrade_tmp_dir }}"
  throttle: 1
  register: download_result
  until: download_result is success
  retries: 3
  delay: 10
    
- name: Download the upgrade image rootfs using wget
  get_url:
    url: "{{ upgrade_rootfs_url }}"
    dest: "{{ upgrade_dir }}"
    checksum: "{{ major_upgrade_rootfs_checksum }}"
    force: true
  environment:
    TMPDIR: "{{ upgrade_tmp_dir }}"
  throttle: 1
  register: download_result
  until: download_result is success
  retries: 3
  delay: 10
