- name: Set download URL
  set_fact:
    upgrade_rootfs_url: 'http://{{ hub_ip }}/updates/major_upgrade/{{ major_upgrade_rootfs_version }}.rootfs.tar.gz'
    upgrade_boot_url: 'http://{{ hub_ip }}/updates/major_upgrade/{{ major_upgrade_rootfs_version }}.boot.tar.gz'    

- name: Download the upgrade image boot fs using wget
  shell: |
    wget -c -O "{{ upgrade_dir }}/$(basename {{ upgrade_boot_url }})" "{{ upgrade_boot_url }}"
  args:
    creates: "{{ upgrade_dir }}/$(basename {{ upgrade_boot_url }})"
    
- name: Download the upgrade image rootfs using wget
  shell: |
    wget -c -O "{{ upgrade_dir }}/$(basename {{ upgrade_rootfs_url }})" "{{ upgrade_rootfs_url }}"
  args:
    creates: "{{ upgrade_dir }}/$(basename {{ upgrade_rootfs_url }})"

