- name: Set facts for hub key
  set_fact:
    hub_privkey: "hub{{ hub_id }}_fleet{{ jaiabot_embedded_fleet_id }}"
    pre_fleetcfg_hub_privkey: "id_hub{{ hub_id }}_fleet{{ jaiabot_embedded_fleet_id }}"

- name: Copy existing hub key to staging
  shell: |
    cd /home/jaia/.ssh
    mkdir -p {{ hub_staging_oldssh_dir }}
    if [ -e {{ hub_privkey }} ]; then
      cp {{ hub_privkey }} {{ hub_staging_oldssh_dir }}/{{ hub_privkey }}
    elif [ -e {{ pre_fleetcfg_hub_privkey }} ]; then
      cp {{ pre_fleetcfg_hub_privkey }} {{ hub_staging_oldssh_dir }}/{{ hub_privkey }}
    fi
    
- name: Check ssh hub key info
  stat:
    path: "{{ hub_staging_oldssh_dir }}/{{ hub_privkey }}"
  register: hub_privkey_file

- name: Fail if ssh hub key does not exist
  include_tasks: handle_failure.yml
  vars:
    error_message: "Hub SSH key does not exist either expected format ({{ hub_staging_oldssh_dir }} or {{ pre_fleetcfg_hub_privkey }}): Please contact JaiaRobotics for a fleet SSH key retrofit."
  when: not hub_privkey_file.stat.exists

- name: Generate fleet config hub ssh key
  shell: |
    mkdir -p {{ hub_staging_dir }}/jaiabot/init
    jaia admin fleet generate --bootdir {{ hub_staging_dir }} {{ staged_fleet_cfg }} hub {{ jaiabot_embedded_hub_id }} --hub-ssh-keys-only
  
- name: Check hub if ssh key matches fleet config ssh key - if so, delete the old key
  shell: |
    existing_hub_privkey_fingerprint=$(ssh-keygen -l -f {{ hub_staging_oldssh_dir }}/{{ hub_privkey }})
    fleet_cfg_hub_privkey_fingerprint=$(ssh-keygen -l -f {{ hub_staging_dir }}/jaiabot/init/{{ hub_privkey }})
    if [ "${existing_hub_privkey_fingerprint}" != "${fleet_cfg_hub_privkey_fingerprint}" ]; then
      echo "Existing hub SSH key does not match hub SSH key in fleet configuration file. Update the fleet configuration file to match the hub SSH key to ensure connectivity."
    else
      echo "Existing hub SSH key matches hub SSH key in fleet configuration file. Removing oldssh key as it's not needed"
      rm -rf {{ hub_staging_oldssh_dir }}
    fi
