# Use the native platform (no --platform=linux/amd64)
ARG distro=@JAIA_VERSION_UBUNTU_CODENAME@
FROM ubuntu:${distro}

ARG distro=@JAIA_VERSION_UBUNTU_CODENAME@
ARG repo=release
ARG version=@JAIA_VERSION_RELEASE_BRANCH@

SHELL ["/bin/bash", "-c"]
ENV DEBIAN_FRONTEND=noninteractive

# Standard build tools - no cross-compiler (gcc-aarch64) needed 
# because we are building ARM on ARM.
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y --no-install-recommends install \
            git build-essential ssh cmake gpg gpg-agent \
            devscripts equivs ca-certificates quilt \
            clang clang-tools dirmngr \
            dput cdbs \
            && rm -rf /var/lib/apt/lists/*

# Add Jaiabot repositories
RUN echo -e "deb http://packages.jaia.tech/ubuntu/${repo}/${version}/ ${distro}/\ndeb http://packages.jaia.tech/ubuntu/gobysoft/${repo}/${version}/ ${distro}/" >> /etc/apt/sources.list.d/jaiabot_${repo}_${version}.list && \
    apt-key adv --recv-key --keyserver keyserver.ubuntu.com 954A004CD5D8CF32 && \
    apt-key adv --recv-key --keyserver keyserver.ubuntu.com 19478082E2F8D3FE

# Install jaiabot dependencies NATIVELY
# Removed all :amd64 and :arm64 suffixes. 
# Apt will automatically grab the native arm64 versions for your Mac.
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get -y install --no-install-recommends \
            libdccl4 \
            libdccl4-dev \
            dccl4-compiler \
            libgoby3 \
            libgoby3-dev \
            libais-dev \
            libgoby3-moos-dev \
            libgoby3-moos \
            libgoby3-gui-dev \
            goby3-interfaces \
            libnanopb-dev \
            nanopb \
            python3-protobuf \
            wget \
            curl \
            graphviz \
            doxygen \
            && \
    rm -rf /var/lib/apt/lists/*

# Allow compilation in git directory
RUN git config --global --add safe.directory /home/jaia/jaiabot

# Arduino CLI & Node setup (unchanged)
RUN curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/local/bin sh -s @JAIA_VERSION_ARDUINO_CLI@ && \
    arduino-cli config init && \
    arduino-cli core update-index && \
    arduino-cli core install arduino:avr

RUN mkdir -p /usr/local/nvm
ENV NVM_DIR=/usr/local/nvm
ENV NODE_VERSION=@JAIA_VERSION_NODEJS@

RUN curl https://raw.githubusercontent.com/creationix/nvm/@JAIA_VERSION_NVM@/install.sh | bash

RUN source $NVM_DIR/nvm.sh \
    && npm install -g npm@@JAIA_VERSION_NPM@ \
    && nvm install $NODE_VERSION \
    && nvm use --delete-prefix $NODE_VERSION \
    && npm i -g webpack webpack-cli

ENV NODE_PATH=$NVM_DIR/versions/node/$NODE_VERSION/bin
ENV PATH=$NODE_PATH:$PATH