- name: Add/update entries in /etc/hosts
  debug:
    msg:  "{{ vpn_ipv6_addresses }}"

- name: Add/update entries in /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '.* {{ item.node_type }}{{ item.node_id }}-virtualfleet{{ cloud_env_vars.jaia_fleet_index }}$'
    line: '{{ item.ip }} {{ item.node_type }}{{ item.node_id }}-virtualfleet{{ cloud_env_vars.jaia_fleet_index }}'
    state: present
  loop: >-
    {%- set result = [] -%}
    {%- for node_type, nodes in vpn_ipv6_addresses.items() -%}
      {%- for node_id, ip in nodes.items() -%}
        {%- set _ = result.append({'node_type': node_type, 'node_id': node_id, 'ip': ip}) -%}
      {%- endfor -%}
    {%- endfor -%}
    {{ result }}
  become: true