    - name: Get current installed version
      shell: "apt-cache policy jaiabot-embedded | grep Installed: | awk '{print $2}'"
      register: current_version

    - name: Get available version to install
      shell: "apt-cache policy jaiabot-embedded | grep Candidate: | awk '{print $2}'"
      register: available_version
      
    - name: Set facts for current and available versions
      set_fact:
        jaiabot_current_version: "{{ current_version.stdout }}"
        jaiabot_available_version: "{{ available_version.stdout }}"
