- name: Install squid-deb-proxy (only on hubs)
  ansible.builtin.apt:
    update_cache: yes
    name: squid-deb-proxy
    state: present

- name: Allow access to packages.jaia.tech from proxy
  ansible.builtin.copy:
    dest: "/etc/squid-deb-proxy/mirror-dstdomain.acl.d/20-jaia"
    content: |
      # network destinations that are allowed by this cache
      packages.jaia.tech

- name: Restart squid-deb-proxy service
  ansible.builtin.systemd:
    name: squid-deb-proxy.service
    state: restarted

- name: Disable unneeded squid default service
  ansible.builtin.systemd:
    name: squid.service
    state: stopped
    enabled: false
