# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goby/middleware/protobuf/can_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from goby.protobuf import option_extensions_pb2 as goby_dot_protobuf_dot_option__extensions__pb2
from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goby/middleware/protobuf/can_config.proto',
  package='goby.middleware.protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n)goby/middleware/protobuf/can_config.proto\x12\x18goby.middleware.protobuf\x1a%goby/protobuf/option_extensions.proto\x1a\x1c\x64\x63\x63l/option_extensions.proto\"\x8a\x03\n\tCanConfig\x12-\n\tinterface\x18\x01 \x02(\tB\x1a\x8a?\x17\xa2\x06\rCan interface\xaa\x06\x04\x63\x61n0\x12=\n\x06\x66ilter\x18\x02 \x03(\x0b\x32-.goby.middleware.protobuf.CanConfig.CanFilter\x12\x12\n\npgn_filter\x18\x03 \x03(\r\x1a\xf0\x01\n\tCanFilter\x12\x0e\n\x06\x63\x61n_id\x18\x01 \x02(\r\x12^\n\x08\x63\x61n_mask\x18\x02 \x01(\x0e\x32\x35.goby.middleware.protobuf.CanConfig.CanFilter.CanMask:\x13\x45xtendedFrameFormatH\x00\x12\x19\n\x0f\x63\x61n_mask_custom\x18\x03 \x01(\rH\x00\"P\n\x07\x43\x61nMask\x12\x18\n\x13StandardFrameFormat\x10\xff\x0f\x12\x1b\n\x13\x45xtendedFrameFormat\x10\xff\xff\xff\xff\x01\x12\x0e\n\x07PGNOnly\x10\x80\xfe\xff\x0f\x42\x06\n\x04mask:\x08\xa2?\x05\xf2\x01\x02si')
  ,
  dependencies=[goby_dot_protobuf_dot_option__extensions__pb2.DESCRIPTOR,dccl_dot_option__extensions__pb2.DESCRIPTOR,])



_CANCONFIG_CANFILTER_CANMASK = _descriptor.EnumDescriptor(
  name='CanMask',
  full_name='goby.middleware.protobuf.CanConfig.CanFilter.CanMask',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='StandardFrameFormat', index=0, number=2047,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ExtendedFrameFormat', index=1, number=536870911,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PGNOnly', index=2, number=33554176,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=437,
  serialized_end=517,
)
_sym_db.RegisterEnumDescriptor(_CANCONFIG_CANFILTER_CANMASK)


_CANCONFIG_CANFILTER = _descriptor.Descriptor(
  name='CanFilter',
  full_name='goby.middleware.protobuf.CanConfig.CanFilter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='can_id', full_name='goby.middleware.protobuf.CanConfig.CanFilter.can_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_mask', full_name='goby.middleware.protobuf.CanConfig.CanFilter.can_mask', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=536870911,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='can_mask_custom', full_name='goby.middleware.protobuf.CanConfig.CanFilter.can_mask_custom', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CANCONFIG_CANFILTER_CANMASK,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='mask', full_name='goby.middleware.protobuf.CanConfig.CanFilter.mask',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=285,
  serialized_end=525,
)

_CANCONFIG = _descriptor.Descriptor(
  name='CanConfig',
  full_name='goby.middleware.protobuf.CanConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='interface', full_name='goby.middleware.protobuf.CanConfig.interface', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\212?\027\242\006\rCan interface\252\006\004can0'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter', full_name='goby.middleware.protobuf.CanConfig.filter', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pgn_filter', full_name='goby.middleware.protobuf.CanConfig.pgn_filter', index=2,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CANCONFIG_CANFILTER, ],
  enum_types=[
  ],
  serialized_options=_b('\242?\005\362\001\002si'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=535,
)

_CANCONFIG_CANFILTER.fields_by_name['can_mask'].enum_type = _CANCONFIG_CANFILTER_CANMASK
_CANCONFIG_CANFILTER.containing_type = _CANCONFIG
_CANCONFIG_CANFILTER_CANMASK.containing_type = _CANCONFIG_CANFILTER
_CANCONFIG_CANFILTER.oneofs_by_name['mask'].fields.append(
  _CANCONFIG_CANFILTER.fields_by_name['can_mask'])
_CANCONFIG_CANFILTER.fields_by_name['can_mask'].containing_oneof = _CANCONFIG_CANFILTER.oneofs_by_name['mask']
_CANCONFIG_CANFILTER.oneofs_by_name['mask'].fields.append(
  _CANCONFIG_CANFILTER.fields_by_name['can_mask_custom'])
_CANCONFIG_CANFILTER.fields_by_name['can_mask_custom'].containing_oneof = _CANCONFIG_CANFILTER.oneofs_by_name['mask']
_CANCONFIG.fields_by_name['filter'].message_type = _CANCONFIG_CANFILTER
DESCRIPTOR.message_types_by_name['CanConfig'] = _CANCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CanConfig = _reflection.GeneratedProtocolMessageType('CanConfig', (_message.Message,), dict(

  CanFilter = _reflection.GeneratedProtocolMessageType('CanFilter', (_message.Message,), dict(
    DESCRIPTOR = _CANCONFIG_CANFILTER,
    __module__ = 'goby.middleware.protobuf.can_config_pb2'
    # @@protoc_insertion_point(class_scope:goby.middleware.protobuf.CanConfig.CanFilter)
    ))
  ,
  DESCRIPTOR = _CANCONFIG,
  __module__ = 'goby.middleware.protobuf.can_config_pb2'
  # @@protoc_insertion_point(class_scope:goby.middleware.protobuf.CanConfig)
  ))
_sym_db.RegisterMessage(CanConfig)
_sym_db.RegisterMessage(CanConfig.CanFilter)


_CANCONFIG.fields_by_name['interface']._options = None
_CANCONFIG._options = None
# @@protoc_insertion_point(module_scope)
