---
- name: Start/Stop VirtualFleet EC2 instances
  hosts: localhost
  gather_facts: yes

  tasks:
    - include_tasks: tasks/read-env.yml
    
    - include_tasks: tasks/instance-state.yml
      vars: 
        - do_wait: false

    - include_tasks: tasks/check-state.yml
