FROM ubuntu:@JAIA_VERSION_UBUNTU_CODENAME@
ARG JAIABOT_APT_REPO="continuous"
ENV jaia_log_dir=/var/log/jaiabot
ENV jaia_mode=simulation
ENV USER=root
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "JAIABOT_APT_REPO = $JAIABOT_APT_REPO"
RUN apt-get update
RUN apt-get install -y git gnupg lsb-release apt-utils vim screen
# Install packages to allow apt to use a repository over HTTPS:
RUN apt-get -y install apt-transport-https ca-certificates curl gnupg lsb-release
ENV GOBYSOFT_SIGNING_KEY=19478082E2F8D3FE
ENV JAIABOT_SIGNING_KEY=954A004CD5D8CF32
RUN default_version=${jaia_version_release_branch}
RUN install -d -m 0755 /etc/apt/keyrings && \
    gpg --keyserver keyserver.ubuntu.com --recv-keys ${GOBYSOFT_SIGNING_KEY} && gpg --export ${GOBYSOFT_SIGNING_KEY} > /etc/apt/keyrings/gobysoft.gpg && \
    gpg --keyserver keyserver.ubuntu.com --recv-keys ${JAIABOT_SIGNING_KEY} && gpg --export ${JAIABOT_SIGNING_KEY} > /etc/apt/keyrings/jaiabot.gpg
# Add packages.gobysoft.org mirror to your apt sources
RUN echo "deb [signed-by=/etc/apt/keyrings/gobysoft.gpg] http://packages.jaia.tech/ubuntu/gobysoft/$JAIABOT_APT_REPO/@JAIA_VERSION_RELEASE_BRANCH@ `lsb_release -c -s`/" | tee /etc/apt/sources.list.d/gobysoft_$JAIABOT_APT_REPO.list
# Use the dev branch for testing, restore above when ready to merge
RUN echo "deb [signed-by=/etc/apt/keyrings/jaiabot.gpg] http://packages.jaia.tech/ubuntu/$JAIABOT_APT_REPO/@JAIA_VERSION_RELEASE_BRANCH@ `lsb_release -c -s`/" | tee /etc/apt/sources.list.d/jaiabot.list
RUN apt-get -y update
# Install the required packages   
RUN apt-get install -y goby3-gui goby3-apps goby3-moos jaiabot-apps jaiabot-python jaiabot-config jaiabot-web moos-ivp-apps moosdb10 libmoos-ivp gpsd wireguard ntpsec ntpstat python3-systemd ansible rsync socat
RUN useradd -mUs /bin/bash jaia
COPY ./entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/bin/bash", "-li", "/entrypoint.sh"]
