/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_JAIABOT_PROTOBUF_ARDUINO_PB_H_INCLUDED
#define PB_JAIABOT_PROTOBUF_ARDUINO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C"
{
#endif

    /* Struct definitions */
    typedef struct _jaiabot_protobuf_ArduinoCommand
    {
        bool has_motor;
        int32_t motor;
        bool has_port_elevator;
        int32_t port_elevator;
        bool has_stbd_elevator;
        int32_t stbd_elevator;
        bool has_rudder;
        int32_t rudder;
        bool has_timeout;
        int32_t timeout;
        bool has_LEDSwitchON;
        bool LEDSwitchON;
        bool has_motor_neutral;
        int32_t motor_neutral;
        bool has_port_elevator_neutral;
        int32_t port_elevator_neutral;
        bool has_stbd_elevator_neutral;
        int32_t stbd_elevator_neutral;
        bool has_rudder_neutral;
        int32_t rudder_neutral;
    } jaiabot_protobuf_ArduinoCommand;

    typedef struct _jaiabot_protobuf_ArduinoResponse
    {
        int32_t code;
        bool has_thermocouple_temperature_C;
        float thermocouple_temperature_C;
        bool has_vccvoltage;
        float vccvoltage;
        bool has_vcccurrent;
        float vcccurrent;
        bool has_vvcurrent;
        float vvcurrent;
        pb_callback_t message;
    } jaiabot_protobuf_ArduinoResponse;

/* Initializer values for message structs */
#define jaiabot_protobuf_ArduinoCommand_init_default                                              \
    {                                                                                             \
        false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, \
            false, 0                                                                              \
    }
#define jaiabot_protobuf_ArduinoResponse_init_default               \
    {                                                               \
        0, false, 0, false, 0, false, 0, false, 0, { {NULL}, NULL } \
    }
#define jaiabot_protobuf_ArduinoCommand_init_zero                                                 \
    {                                                                                             \
        false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, \
            false, 0                                                                              \
    }
#define jaiabot_protobuf_ArduinoResponse_init_zero                  \
    {                                                               \
        0, false, 0, false, 0, false, 0, false, 0, { {NULL}, NULL } \
    }

/* Field tags (for use in manual encoding/decoding) */
#define jaiabot_protobuf_ArduinoCommand_motor_tag 1
#define jaiabot_protobuf_ArduinoCommand_port_elevator_tag 2
#define jaiabot_protobuf_ArduinoCommand_stbd_elevator_tag 3
#define jaiabot_protobuf_ArduinoCommand_rudder_tag 4
#define jaiabot_protobuf_ArduinoCommand_timeout_tag 5
#define jaiabot_protobuf_ArduinoCommand_LEDSwitchON_tag 6
#define jaiabot_protobuf_ArduinoCommand_motor_neutral_tag 20
#define jaiabot_protobuf_ArduinoCommand_port_elevator_neutral_tag 21
#define jaiabot_protobuf_ArduinoCommand_stbd_elevator_neutral_tag 22
#define jaiabot_protobuf_ArduinoCommand_rudder_neutral_tag 23
#define jaiabot_protobuf_ArduinoResponse_code_tag 1
#define jaiabot_protobuf_ArduinoResponse_thermocouple_temperature_C_tag 2
#define jaiabot_protobuf_ArduinoResponse_message_tag 20
#define jaiabot_protobuf_ArduinoResponse_vccvoltage_tag 3
#define jaiabot_protobuf_ArduinoResponse_vcccurrent_tag 4
#define jaiabot_protobuf_ArduinoResponse_vvcurrent_tag 5

/* Struct field encoding specification for nanopb */
#define jaiabot_protobuf_ArduinoCommand_FIELDLIST(X, a)       \
    X(a, STATIC, OPTIONAL, SINT32, motor, 1)                  \
    X(a, STATIC, OPTIONAL, SINT32, port_elevator, 2)          \
    X(a, STATIC, OPTIONAL, SINT32, stbd_elevator, 3)          \
    X(a, STATIC, OPTIONAL, SINT32, rudder, 4)                 \
    X(a, STATIC, OPTIONAL, SINT32, timeout, 5)                \
    X(a, STATIC, OPTIONAL, BOOL, LEDSwitchON, 6)              \
    X(a, STATIC, OPTIONAL, SINT32, motor_neutral, 20)         \
    X(a, STATIC, OPTIONAL, SINT32, port_elevator_neutral, 21) \
    X(a, STATIC, OPTIONAL, SINT32, stbd_elevator_neutral, 22) \
    X(a, STATIC, OPTIONAL, SINT32, rudder_neutral, 23)
#define jaiabot_protobuf_ArduinoCommand_CALLBACK NULL
#define jaiabot_protobuf_ArduinoCommand_DEFAULT NULL

#define jaiabot_protobuf_ArduinoResponse_FIELDLIST(X, a)         \
    X(a, STATIC, REQUIRED, SINT32, code, 1)                      \
    X(a, STATIC, OPTIONAL, FLOAT, thermocouple_temperature_C, 2) \
    X(a, STATIC, OPTIONAL, FLOAT, vccvoltage, 3)                 \
    X(a, STATIC, OPTIONAL, FLOAT, vcccurrent, 4)                 \
    X(a, STATIC, OPTIONAL, FLOAT, vvcurrent, 5)                  \
    X(a, CALLBACK, OPTIONAL, STRING, message, 20)
#define jaiabot_protobuf_ArduinoResponse_CALLBACK pb_default_field_callback
#define jaiabot_protobuf_ArduinoResponse_DEFAULT NULL

    extern const pb_msgdesc_t jaiabot_protobuf_ArduinoCommand_msg;
    extern const pb_msgdesc_t jaiabot_protobuf_ArduinoResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define jaiabot_protobuf_ArduinoCommand_fields &jaiabot_protobuf_ArduinoCommand_msg
#define jaiabot_protobuf_ArduinoResponse_fields &jaiabot_protobuf_ArduinoResponse_msg

/* Maximum encoded size of messages (where known) */
#define jaiabot_protobuf_ArduinoCommand_size 60
    /* jaiabot_protobuf_ArduinoResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
