syntax = "proto2";

import "dccl/option_extensions.proto";

package jaiabot.protobuf;

enum MotorHarnessType
{
    NONE = 1;
    RPM_AND_THERMISTOR = 2;
}

message Motor
{
    message Thermistor {
        optional float temperature = 1 [
            (dccl.field) = {
                min: -50
                max: 200
                precision: 2
                units { derived_dimensions: "temperature" system: "celsius" }
            }
        ];
        optional float resistance = 2 [
            (dccl.field) = {
                min: 0
                max: 100000
                precision: 1
                units { system: "si" }
            }
        ];
        optional float voltage = 3 [
            (dccl.field) = {
                min: 0
                max: 5
                precision: 3
                units { system: "si" }
            }
        ];
    }

    optional double rpm = 1;
    optional Thermistor thermistor = 2;
    optional MotorHarnessType motor_harness_type = 3 [default = NONE];
}
