syntax = "proto2";

import "jaiabot/messages/option_extensions.proto";

package jaiabot.protobuf;

// also must match jaiabot/debian/jaiabot-embedded.templates:
//   jaiabot-embedded/type
enum NodeType
{
    HUB = 0;
    BOT = 1;
}

// also must match jaiabot/debian/jaiabot-embedded.templates:
//   jaiabot-embedded/bot_type
enum BotType
{
    HYDRO = 1 [(jaia.ev).rest_api.presence = GUARANTEED];
    ECHO = 2 [(jaia.ev).rest_api.presence = GUARANTEED];
    BIO = 3 [(jaia.ev).rest_api.presence = GUARANTEED];
    STORM = 4 [(jaia.ev).rest_api.presence = GUARANTEED];
}
