syntax = "proto2";

import "dccl/option_extensions.proto";
import "nanopb.proto";

package jaiabot.protobuf;

enum PowerBoardMCUCommand
{
    ENTER_BOOTLOADER_MODE = 1;
}

message Metadata {
    option (dccl.msg) = {
        unit_system: "si"
    };

    optional int32 power_board_version = 1;

    message MetadataValue
    {
        required string key = 1 [(nanopb).max_size = 16];
        required string value = 2 [(nanopb).max_size = 64];
    }

    repeated MetadataValue metadata = 2 [(nanopb).max_count = 16];
    optional bool init_failed = 3;
}

message PowerBoardRequest {
    option (dccl.msg) = {
        unit_system: "si"
    };

    required uint64 time = 1 [
        (dccl.field) = { units { prefix: "micro" derived_dimensions: "time" } }
    ];

    optional bool request_metadata = 2;
    optional PowerBoardMCUCommand mcu_command = 3;
}

message PowerBoardMessage {
    option (dccl.msg) = {
        unit_system: "si"
    };

    required uint64 time = 1 [
        (dccl.field) = { units { prefix: "micro" derived_dimensions: "time" } }
    ];

    oneof data 
    {
        Metadata metadata = 11;
    }
}