syntax = "proto2";

import "dccl/option_extensions.proto";
import "jaiabot/messages/imu.proto";  
import "jaiabot/messages/pressure_temperature.proto"; 
import "jaiabot/messages/motor.proto";

package jaiabot.protobuf;

enum ProductionCommand 
{ 
  TEST_IMU_SENSOR = 1;
  TEST_PRESSURE_SENSOR = 2;
  TEST_MOTOR_HARNESS = 3;
}

message ProductionRequest 
{ 
  option (dccl.msg) = { unit_system: "si" }; 

  required uint64 time = 1 [ 
    (dccl.field) = { units { prefix: "micro" derived_dimensions: "time" } } 
  ]; 

  oneof request 
  { 
    ProductionCommand production_command = 11; 
  } 
}

message ProductionResponse 
{ 
  option (dccl.msg) = { unit_system: "si" }; 
  optional ProductionCommand production_command = 1;

  required uint64 time = 2 [ 
    (dccl.field) = { units { prefix: "micro" derived_dimensions: "time" } } 
  ]; 

  oneof data 
  { 
    IMUData imu_report = 11; 
    PressureAdjustedData pressure_report = 12; 
    Motor motor_harness_report = 13;
  } 
  optional string test_result = 3;
  optional string response = 4;
}
