syntax = "proto2";

import "goby/middleware/protobuf/gpsd.proto";

import "dccl/option_extensions.proto";

import "jaiabot/messages/option_extensions.proto";
import "jaiabot/messages/mission.proto";
import "jaiabot/messages/sensor/blue_robotics__bar30.proto";
import "jaiabot/messages/sensor/atlas_scientific__oem_ec.proto";

package jaiabot.protobuf;

enum StormMissionState
{
    STARTING_UP = 0;
    ACTIVATING = 1;
    MISSION_RUNNING = 2;

    SELF_TEST__IN_WATER_DETECTION = 100;
    SELF_TEST__LAUNCH_TUBE_DETECTION = 101;
    SELF_TEST__LAUNCH_TUBE_RECOVERY = 102;
    SELF_TEST__PARACHUTE_ATTACHMENT_DETECTION = 103;
    SELF_TEST__PARACHUTE_ATTACHMENT_RECOVERY = 104;
    SELF_TEST__AIR_DESCENT_DATA_OFFLOAD = 105;
    SELF_TEST__WRAPUP = 106;

    MISSION_PLANNING__WAIT_FOR_MISSION_MANAGER = 200;
    MISSION_PLANNING__WAIT_FOR_REMOTE_MISSION = 201;
    MISSION_PLANNING__SEND_MISSION = 202;

    SLEEP_PREP__DATA_OFFLOAD = 300;
    SLEEP_PREP__WRAPUP = 301;
}

message StormMission
{
    option (dccl.msg) = {
        unit_system: "si"
    };

    required MissionTask.DiveParameters dive = 10;

    required uint32 sleep_for_minutes = 20 [(dccl.field) = {
        min: 0
        max: 10080  // week
        units { unit: "metric::minute" }
    }];

    optional uint32 min_battery_percentage = 30
        [default = 10, (dccl.field) = { min: 0 max: 99 }];

    optional uint32 remote_mission_wait_minutes = 40 [
        default = 0,
        (dccl.field) = {
            min: 0
            max: 60
            units { unit: "metric::minute" }
        }
    ];

    optional uint32 data_offload_timeout_minutes = 50 [
        default = 60,
        (dccl.field) = {
            min: 0
            max: 600
            units { unit: "metric::minute" }
        }
    ];

    message Threshold
    {
        enum Stat
        {
            MEAN = 1;
            MEDIAN = 2;
            STDDEV = 3;
        }

        enum Condition
        {
            IGNORE = 0;
            GREATER_THAN = 1;
            LESS_THAN = 2;
        }

        message Check
        {
            optional Condition condition = 1 [default = IGNORE];
            optional Stat stat = 2 [default = MEAN];

            oneof value
            {
                double conductivity = 10
                    [(dccl.field) = { min: 0 max: 60000 precision: -1 }];
                // REQUIRES DCCL 4.3.1 - uncomment when we wrap this in
                // [(dccl.field) = {
                // units {
                //         custom {
                //             unit: "jaiabot::units::microsiemens_per_cm_unit"
                //             header: "jaiabot/units/conductivity.h"
                //         }
                //     }
                // }];
                double pressure = 11 [(dccl.field) = {
                    min: -10
                    max: 100
                    precision: 1
                    units { prefix: "deci" unit: "metric::bar" }
                }];

                double gps_altitude = 12 [(dccl.field) = {
                    min: -10
                    max: 1000
                    precision: -1
                    units { derived_dimensions: "length" }
                }];
            }

            optional double hold_time = 3 [
                default = 0,
                (dccl.field) = {
                    min: 0
                    max: 600
                    precision: 0
                    units { derived_dimensions: "time" }
                }
            ];
        }
        repeated Check check = 1 [(dccl.field).max_repeat = 5];
    }

    message InWaterDetectionParams
    {
        required Threshold threshold = 1;
    }
    optional InWaterDetectionParams in_water =
        60;  // required for initial mission, unused for updates

    message LaunchTubeDetectionParams
    {
        required Threshold cleared_threshold = 1;
        required Threshold stuck_threshold = 2;

        message Action
        {
            required int32 thrust_percentage = 1
                [(dccl.field) = { min: -100 max: 100 }];

            required uint32 thrust_duration = 2 [
                default = 5,
                (dccl.field) = {
                    min: 0
                    max: 60
                    units { base_dimensions: "T" }
                }
            ];
            optional uint32 count = 3
                [default = 1, (dccl.field) = { min: 1 max: 10 }];
        }

        repeated Action recovery_action = 3 [(dccl.field) = { max_repeat: 10 }];
    }
    optional LaunchTubeDetectionParams launch_tube =
        61;  // required for initial mission, unused for updates

    message ParachuteAttachmentDetectionParams
    {
        required Threshold cleared_threshold = 1;
        required Threshold entangled_threshold = 2;

        message Action
        {
            required int32 thrust_percentage = 1
                [(dccl.field) = { min: -100 max: 100 }];

            required uint32 thrust_duration = 2 [
                default = 5,
                (dccl.field) = {
                    min: 0
                    max: 60
                    units { base_dimensions: "T" }
                }
            ];
            optional uint32 count = 3
                [default = 1, (dccl.field) = { min: 1 max: 10 }];
        }

        repeated Action recovery_action = 3 [(dccl.field) = { max_repeat: 10 }];
    }

    optional ParachuteAttachmentDetectionParams parachute =
        62;  // required for initial mission, unused for updates
}

message StormMissionUpdate
{
    enum UpdateType
    {
        UPDATE_MISSION = 1;

        // TODO: Implement
        ABORT = 2;
        PAUSE = 3;
        RESUME = 4;
        DELAY = 5;
    }
    required UpdateType type = 1;

    oneof update_data
    {
        // required when type == UPDATE_MISSION
        StormMission new_mission = 10;

        // required when type == DELAY
        uint32 delay_for_minutes = 20 [(dccl.field) = {
            min: 1
            max: 1440  // day
            units { unit: "metric::minute" }
        }];
    }
}

message StormMissionReport
{
    option (dccl.msg) = {
        unit_system: "si"
    };

    required StormMissionState state = 10;
}

message StormMissionStateChange
{
    required StormMissionState state = 1;

    enum Direction
    {
        ENTERED = 1;
        EXITED = 2;
    }

    required Direction direction = 2;
}

// added to BotStatus
message StormStatus
{
    option (dccl.msg) = {
        unit_system: "si"
    };

    required StormMissionState mission_state = 10;
}

enum StormMissionSimulatorStage
{
    AIR_DESCENT = 1;
    IN_WATER = 2;
}
