syntax = "proto2";

import "jaiabot/messages/option_extensions.proto";

package jaiabot.protobuf;

enum StormState
{
    STARTING_UP = 0;
    ACTIVATING = 1;
    MISSION_RUNNING = 2;

    SELF_TEST__IN_WATER_DETECTION = 100;
    SELF_TEST__LAUNCH_TUBE_DETECTION = 101;
    SELF_TEST__LAUNCH_TUBE_RECOVERY = 102;
    SELF_TEST__PARACHUTE_ATTACHMENT_DETECTION = 103;
    SELF_TEST__PARACHUTE_ATTACHMENT_RECOVERY = 104;
    SELF_TEST__AIR_DESCENT_DATA_OFFLOAD = 105;
    SELF_TEST__WRAPUP = 106;

    MISSION_PLANNING__WAIT_FOR_MISSION_MANAGER = 200;
    MISSION_PLANNING__WAIT_FOR_REMOTE_MISSION = 201;
    MISSION_PLANNING__SEND_MISSION = 202;

    SLEEP_PREP__DATA_OFFLOAD = 300;
    SLEEP_PREP__WRAPUP = 301;    

}

