syntax="proto2";
import "jaiabot/messages/imu.proto";
import "jaiabot/messages/sensor/salinity.proto";
import "jaiabot/messages/sensor/pressure_temperature.proto";
import "jaiabot/messages/tsys01.proto";
import "jaiabot/messages/echo.proto";
import "jaiabot/messages/ppk.proto";

package jaiabot.protobuf;


message UDPGatewayEnvelope
{
    oneof payload
    {
        IMUCommand imu_command = 1;
        IMUData imu_data = 2;

        SalinityData salinity_data = 3;

        PressureTemperatureData pressure_temperature_data = 4;

        TSYS01Data tsys01_data = 5;

        EchoCommand echo_command = 6;
        EchoData echo_data = 7;

        // jaiabot_ubx_ppk.py
        UBXChunk ubx_chunk = 8;

    }

}

