syntax="proto2";
import "jaiabot/messages/imu.proto";
import "jaiabot/messages/sensor/salinity.proto";
import "jaiabot/messages/sensor/pressure_temperature.proto";
import "jaiabot/messages/tsys01.proto";
import "jaiabot/messages/echo.proto";
import "jaiabot/messages/jaia_dccl.proto";
import "goby/middleware/protobuf/gpsd.proto";
import "jaiabot/messages/arduino.proto";
import "jaiabot/messages/mission.proto";

package jaiabot.protobuf;


message UDPGatewayEnvelope
{
    message SurobCurrentsPayload
    {
        oneof payload
        {
            // current estimate from Python app
            TaskPacket task_packet = 1;
            
            // data messages sent to Python app, logged to compute current estimate
            ArduinoResponse arduino_response = 2;
            PressureTemperatureData pressure_temperature_data = 3;
            goby.middleware.protobuf.gpsd.TimePositionVelocity time_position_velocity = 4;

            // mission state sent to Python app to start/stop data logging
            MissionReport mission_report = 5;
        }
    }
    
    oneof payload
    {
        IMUCommand imu_command = 1;
        IMUData imu_data = 2;

        SalinityData salinity_data = 3;

        PressureTemperatureData pressure_temperature_data = 4;

        TSYS01Data tsys01_data = 5;

        EchoCommand echo_command = 6;
        EchoData echo_data = 7;

        SurobCurrentsPayload surob_currents_payload = 8;
    }

}

