#!/bin/bash
set -e

. /usr/share/debconf/confmodule

db_get jaiabot-embedded/type
JAIA_TYPE=$RET

db_get jaiabot-embedded/bot_type
JAIA_BOT_TYPE=$RET

if [ "$JAIA_TYPE" = "bot" ]; then
    db_get jaiabot-embedded/bot_id
    BOT_OR_HUB_INDEX=$RET
    if [ "$JAIA_BOT_TYPE" = "none" ]; then
        JAIA_BOT_TYPE="hydro"
        db_set jaiabot-embedded/bot_type "hydro"
    fi

elif [ "$JAIA_TYPE" = "hub" ]; then
    db_get jaiabot-embedded/hub_id
    BOT_OR_HUB_INDEX=$RET
    JAIA_BOT_TYPE="none"
    db_set jaiabot-embedded/bot_type "none"
fi

db_get jaiabot-embedded/fleet_id
FLEET_INDEX=$RET

# WLAN (fleet) addressing, as defined by the 'jaia_ip' tool
NODE_WLAN_IP=$(/usr/bin/jaia_ip --query_type addr --node_type ${JAIA_TYPE} --node_id ${BOT_OR_HUB_INDEX} --ip_net wlan --fleet_id ${FLEET_INDEX} --ip_version ipv4)
FLEET_WLAN_NET=$(/usr/bin/jaia_ip --query_type net --ip_net wlan --fleet_id ${FLEET_INDEX} --ip_version ipv4)
HUB0_WLAN_IP=$(/usr/bin/jaia_ip --query_type addr --node_type hub --node_id 0 --ip_net wlan --fleet_id ${FLEET_INDEX} --ip_version ipv4)

OLD_HOST_NAME=`/bin/hostname`
NEW_HOST_NAME=${JAIA_TYPE}${BOT_OR_HUB_INDEX}-fleet${FLEET_INDEX}

if [[ "$NEW_HOST_NAME" != "$OLD_HOST_NAME" ]]; then
    echo ">>>>> Setting hostname to $NEW_HOST_NAME (log out and in again for the prompt to change) ... "
     /usr/bin/hostnamectl set-hostname $NEW_HOST_NAME
     sed -i "s/^\(127\.0\.[0-9\.]*\).*${OLD_HOST_NAME}$/\1\t${NEW_HOST_NAME}/" /etc/hosts
     sed -i "s/^\(10\.23\.[0-9\.]*\).*${OLD_HOST_NAME}$/${NODE_WLAN_IP} ${NEW_HOST_NAME}/" /etc/hosts
    echo "<<<<< Setting hostname complete!"
fi

echo ">>>>> Updating wifi configuration ... "

FLEET_WLAN_SSID="JAIA-HUB-WIFI-${FLEET_INDEX}"
NETENV_FILE=/etc/jaiabot/network.env
FLEET_ADDRESS="${NODE_WLAN_IP}/${FLEET_WLAN_NET##*/}"
FLEET_GATEWAY=$(/usr/bin/jaia_ip --query_type addr --node_type gateway --ip_net wlan --fleet_id ${FLEET_INDEX} --ip_version ipv4)

# In place upgrades from 1.y -> 2.y won't have /etc/jaiabot/network.env, so we need to create it
if [ ! -f "${NETENV_FILE}" ]; then
    # if possible, read existing wifi password
    OLD_WLAN_NETWORK_FILE="/etc/network/interfaces.d/wlan0"
    if [ -f "${OLD_WLAN_NETWORK_FILE}" ]; then
        FLEET_PASSWORD=$(sed -n 's/ *wpa-psk *.\(.*\)/\1/p')
    fi
    cat <<EOF > ${NETENV_FILE}
jaia_network_fleet_ssid="${FLEET_WLAN_SSID}"
jaia_network_fleet_password="${FLEET_PASSWORD}"
jaia_network_fleet_address="${FLEET_ADDRESS}"
jaia_network_fleet_gateway="${FLEET_GATEWAY}"
jaia_network_wifi_iface=wlan0
jaia_network_eth_iface=eth0
jaia_network_service_ssid="JaiaService"
jaia_network_service_password="jaia_service"
jaia_network_eth_enabled=false
EOF
else
    sed -i "s/fleet_ssid=.*/fleet_ssid=\"${FLEET_WLAN_SSID}\"/" ${NETENV_FILE}
    sed -i "s|fleet_address=.*|fleet_address=\"${FLEET_ADDRESS}\"|" ${NETENV_FILE}
    sed -i "s/fleet_gateway=.*/fleet_gateway=\"${FLEET_GATEWAY}\"/" ${NETENV_FILE}
fi

/usr/bin/jaia_update_network.sh


echo "<<<<< Updating wifi configuration complete (IP address changes won't take effect until reboot)!"
echo ">>>>> Updating hub0 address ... "
sed -i "s/.*hub0/${HUB0_WLAN_IP} hub0/" /etc/hosts
echo "<<<<< Updating hub0 address complete!"


echo ">>>>> Installing and enabling systemd services ... "
# Install systemd services and enable them
db_get jaiabot-embedded/mode
JAIA_MODE=$RET

SYSTEMD_SIM_FLAG=""
if [[ "$JAIA_MODE" = "simulation" ]]; then
    db_get jaiabot-embedded/warp
    JAIA_WARP=$RET

    SYSTEMD_SIM_FLAG="--simulation --warp ${JAIA_WARP}"
fi

db_get jaiabot-embedded/led_type
JAIA_LED_TYPE=$RET

db_get jaiabot-embedded/electronics_stack
JAIA_ELECTRONICS_STACK=$RET

db_get jaiabot-embedded/user_role
JAIA_USER_ROLE=$RET

db_get jaiabot-embedded/imu_type
JAIA_IMU_TYPE=$RET

db_get jaiabot-embedded/imu_install_type
JAIA_IMU_INSTALL_TYPE=$RET

db_get jaiabot-embedded/arduino_type
JAIA_ARDUINO_TYPE=$RET

db_get jaiabot-embedded/pam_connection_type
JAIA_PAM_CONNECTION_TYPE=$RET

db_get jaiabot-embedded/data_offload_ignore_type
JAIA_DATA_OFFLOAD_IGNORE_TYPE=$RET

db_get jaiabot-embedded/motor_harness_type
JAIA_MOTOR_HARNESS_TYPE=$RET

db_get jaiabot-embedded/temperature_sensor_type
JAIA_TEMPERATURE_SENSOR_TYPE=$RET

db_get jaiabot-embedded/pressure_sensor_type
JAIA_PRESSURE_SENSOR_TYPE=$RET

db_get jaiabot-embedded/rf_encryption_password
JAIA_RF_ENCRYPTION_PASSWORD=$RET

db_get jaiabot-embedded/comms_links
JAIA_COMMS_LINKS="$(echo $RET | sed 's/,/ /g')"

db_get jaiabot-embedded/camera_positions
JAIA_CAMERA_POSITIONS="$(echo $RET | sed 's/,/ /g')"

db_get jaiabot-embedded/dccl_encryption_password
JAIA_DCCL_ENCRYPTION_PASSWORD=$RET

db_get jaiabot-embedded/additional_sensors
JAIA_ADDITIONAL_SENSORS="$(echo $RET | sed 's/,/ /g')"

/usr/share/jaiabot/config/gen/systemd.py ${JAIA_TYPE} \
                                         --enable \
                                         --jaiabot_bin_dir=/usr/bin \
                                         --jaiabot_share_dir=/usr/share \
                                         --goby_bin_dir=/usr/bin \
                                         --moos_bin_dir=/usr/bin \
                                         --gen_dir=/usr/share/jaiabot/config/gen \
                                         --systemd_dir=/usr/lib/systemd/system \
                                         --bot_index=${BOT_OR_HUB_INDEX} \
                                         --hub_index=${BOT_OR_HUB_INDEX} \
                                         --fleet_index=${FLEET_INDEX} \
                                         ${SYSTEMD_SIM_FLAG} \
                                         --led_type=${JAIA_LED_TYPE} \
                                         --electronics_stack=${JAIA_ELECTRONICS_STACK} \
                                         --user_role=${JAIA_USER_ROLE} \
                                         --imu_type=${JAIA_IMU_TYPE} \
                                         --arduino_type=${JAIA_ARDUINO_TYPE} \
                                         --pam_connection_type=${JAIA_PAM_CONNECTION_TYPE} \
                                         --bot_type=${JAIA_BOT_TYPE} \
                                         --imu_install_type=${JAIA_IMU_INSTALL_TYPE} \
                                         --data_offload_ignore_type=${JAIA_DATA_OFFLOAD_IGNORE_TYPE} \
                                         --motor_harness_type=${JAIA_MOTOR_HARNESS_TYPE} \
                                         --temperature_sensor_type=${JAIA_TEMPERATURE_SENSOR_TYPE} \
                                         --pressure_sensor_type=${JAIA_PRESSURE_SENSOR_TYPE} \
                                         --rf_encryption_password=${JAIA_RF_ENCRYPTION_PASSWORD} \
                                         --comms_links ${JAIA_COMMS_LINKS} \
                                         --camera_positions ${JAIA_CAMERA_POSITIONS} \
                                         --dccl_encryption_password=${JAIA_DCCL_ENCRYPTION_PASSWORD} \
                                         --additional_sensors ${JAIA_ADDITIONAL_SENSORS}

echo "<<<<< Installing and enabling systemd services complete!"

shopt -s nullglob

echo ">>>>> Stopping, disabling, and removing jaia gps systemd services if they exist ... "
for service_file in /usr/lib/systemd/system/gps_*.service; do
    service_name=$(basename $service_file)
    echo "Stopping $service_name"
    /bin/systemctl stop $service_name || true
    echo "Disabling $service_name"
    /bin/systemctl disable $service_name
    echo "Removing $service_file"
    rm $service_file
done

echo ">>>>> Starting jaia firmware systemd services ... "
for service_file in /usr/lib/systemd/system/jaia_firm*.service; do
    service_name=$(basename $service_file)
    echo "Starting $service_name"
    if [ "$service_name" != "jaia_firm_hub-button-led-poweroff_py.service" ]; then
        /bin/systemctl start $service_name || true
    fi
done

echo ">>>>> Restarting gpsd"
/bin/systemctl restart gpsd.service

if [ "$JAIA_TYPE" = "bot" ]; then
    if [[ "$JAIA_ARDUINO_TYPE" != "none" ]]; then
        echo ">>>>> Flashing Arduino ..."
        /usr/share/jaiabot/arduino/jaiabot_runtime/${JAIA_ARDUINO_TYPE}/upload.sh
        echo "<<<<< Flashing Arduino complete!"
    fi
fi


echo ">>>>> Installing (but not enabling) Wireguard VPN ... "

/usr/share/jaiabot/config/gen/wireguard.py ${JAIA_TYPE} \
                                         --name wg_jaia \
                                         --bot_index=${BOT_OR_HUB_INDEX} \
                                         --hub_index=${BOT_OR_HUB_INDEX} \
                                         --fleet_index=${FLEET_INDEX}

echo ">>>>> Installing Wireguard VPN complete!"

alias_name="j"
alias_command="jaiabot-status"

# Check if the alias already exists in .bashrc
if ! grep -q "alias $alias_name=" /home/jaia/.bashrc; then
  # Add the alias to .bashrc
  echo "alias $alias_name=\"$alias_command\"" >> /home/jaia/.bashrc
  echo "Alias added to /home/jaia/.bashrc"
else
  echo "jaiabot-status Alias already exists in /home/jaia/.bashrc"
fi

runtime_src_command="set -a; source /etc/jaiabot/runtime.env; set +a"
if ! grep -q "$runtime_src_command" /home/jaia/.bashrc; then
  echo "$runtime_src_command" >> /home/jaia/.bashrc
  echo "source runtime.env added to /home/jaia/.bashrc"
else
  echo "source runtime.env already exists in /home/jaia/.bashrc"
fi


echo "jaiabot-embedded version: $(dpkg-query --show --showformat='${Version}' jaiabot-embedded)" > /etc/jaiabot/software_version

if [ ! -f /etc/apt/apt.conf.d/99disable-auto-upgrades ]; then
    echo 'APT::Periodic::Update-Package-Lists "0";' > /etc/apt/apt.conf.d/99disable-auto-upgrades
    echo 'APT::Periodic::Unattended-Upgrade "0";' >> /etc/apt/apt.conf.d/99disable-auto-upgrades
    systemctl disable --now apt-daily.timer apt-daily-upgrade.timer
fi

#DEBHELPER#

exit 0
