#!/bin/bash
set -e

echo ">>>>> Stopping jaiabot app software ... "
/bin/systemctl stop jaiabot || true
echo "<<<<< Stopping jaiabot app software complete! ... "

shopt -s nullglob

services_to_disable=()
service_files=()
for service_file in /usr/lib/systemd/system/jaia*.service; do
    services_to_disable+=("$(basename $service_file)")
    service_files+=("$service_file")
done

echo ">>>>> Stopping, disabling, and removing jaia systemd services ... "

for service_name in "${services_to_disable[@]}"; do
    echo "Stopping $service_name"
    /bin/systemctl stop $service_name || true
done

if [ ${#services_to_disable[@]} -gt 0 ]; then
    echo "Disabling ${services_to_disable[@]}"
    /bin/systemctl disable "${services_to_disable[@]}"
fi

for service_file in "${service_files[@]}"; do
    echo "Removing $service_file"
    rm $service_file
done

echo "<<<<< Stopping, disabling, and removing jaia systemd services complete! ... "

#DEBHELPER#

exit 0
