export enum GlobalActions {
    SAVED_CLIENT_ID = "SAVED_CLIENT_ID",
    TAKE_CONTROL_SUCCESS = "TAKE_CONTROL_SUCCESS",
    EXITED_RC_MODE = "EXITED_RC_MODE",
    CLOSED_HUB_DETAILS = "CLOSED_HUB_DETAILS",
    CLICKED_HUB_TAB = "CLICKED_HUB_TAB",
    CLICKED_BOT_TAB = "CLICKED_BOT_TAB",
    CLICKED_HUB_MAP_ICON = "CLICKED_HUB_MAP_ICON",
    CLICKED_BOT_MAP_ICON = "CLICKED_BOT_MAP_ICON",
    CLICKED_HUB_ACCORDION = "CLICKED_HUB_ACCORDION",
}
