#!/usr/bin/env bash

# Intended to be installed to /etc/update-motd.d to be display in the MOTD (login message)

# https://patorjk.com/software/taag/#p=display&f=Mini&t=JAIABOT

echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
echo "                             ___       _   _ ___             "
echo "                      |  /\   |   /\  |_) / \ |              "
echo "                    \_| /--\ _|_ /--\ |_) \_/ |              "
echo ""
echo "                       https://www.jaia.tech/                    "
echo "                   https://github.com/jaiarobotics/              "
export SYSTEMD_COLORS=1
echo "                           _ ___  _                              "
echo "                          |_  |  |_) |\/|                        "
echo "                          |  _|_ | \ |  |                        "
echo ""
systemctl list-units -all "jaia_firm*" --no-pager
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
echo "                               _   _   __ "
echo "                          /\  |_) |_) (_  "
echo "                         /--\ |   |   __) "
echo "                                          "
systemctl list-units -all "jaiabot*" --no-pager
echo "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"
echo "                       _  _   __ ___  _        __ "
echo "                 \  / |_ |_) (_   |  / \ |\ | (_  "
echo "                  \/  |_ | \ __) _|_ \_/ | \| __) "      
echo ""

jaia_tool=jaia
# pam_motd does not run /etc/profile.d, so source the identity file directly
if [ -e /etc/jaiabot/jaia.env ]; then
set -a
source /etc/jaiabot/jaia.env
set +a
fi

${jaia_tool} version

echo
echo ">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
