#!/bin/bash

# Writes the fleet DNS configuration served by the jaiabot_dns service, and
# points this machine's resolver at it.

set -u -e

root=""
type=""
node_id=""
fleet=""
mode=""

function usage {
    cat >&2 <<EOF
Usage: $(basename $0) [-t type] [-i node_id] [-f fleet_id] [-m mode] [-o root]

Generates /etc/jaiabot/dnsmasq.conf and /etc/jaiabot/dns-hosts, which resolve
every bot and hub name in this fleet ("bot3", "hub1", "hub1-fleet2", and the
same names under the fleet DNS domain), and writes /etc/resolv.conf so that
this machine uses them.

Only a physical hub of a runtime fleet serves DNS; anything else undoes a
resolv.conf written by an earlier run and exits.

  -t  bot or hub
  -i  bot or hub id
  -f  fleet id
  -m  runtime or simulation
  -o  write below this directory rather than /

The identity options default to this machine's, read from
/etc/jaiabot/jaia.env or the jaiabot-embedded debconf database. Maintainer
scripts must pass them: debconf does not write the running script's answers to
the on-disk database until it exits.
EOF
}

while getopts "t:i:f:m:o:h" opt; do
    case $opt in
        t) type=$OPTARG ;;
        i) node_id=$OPTARG ;;
        f) fleet=$OPTARG ;;
        m) mode=$OPTARG ;;
        o) root=$OPTARG ;;
        h) usage; exit 0 ;;
        *) usage; exit 1 ;;
    esac
done

network_env=/etc/jaiabot/network.env
jaia_env=/etc/jaiabot/jaia.env
debconf_helper=/usr/bin/jaia-debconf.sh

if [ -r "${jaia_env}" ]; then
    set -a; source "${jaia_env}"; set +a
fi

if [ -r "${network_env}" ]; then
    set -a; source "${network_env}"; set +a
fi

if [ -r "${debconf_helper}" ]; then
    source "${debconf_helper}"
else
    function jaia_debconf_get { echo "$2"; }
fi

type=${type:-${jaia_type:-$(jaia_debconf_get type "")}}
fleet=${fleet:-${jaia_fleet_id:-$(jaia_debconf_get fleet_id "")}}
mode=${mode:-$(jaia_debconf_get mode runtime)}

if [ "${type}" = "hub" ]; then
    node_id=${node_id:-${jaia_hub_id:-$(jaia_debconf_get hub_id "")}}
else
    node_id=${node_id:-${jaia_bot_id:-$(jaia_debconf_get bot_id "")}}
fi

dnsmasq_conf=${root}/etc/jaiabot/dnsmasq.conf
dns_hosts=${root}/etc/jaiabot/dns-hosts
resolv_conf=${root}/etc/resolv.conf

generated_by="# Generated by $(basename $0) - do not edit"

# Upstream for everything that isn't a fleet name. Taken from the resolver this
# machine already uses (which the image, cloud-init or a previous run of this
# script wrote), so an IPv6-only or otherwise non-default host keeps working.
function upstream_nameservers {
    local upstream

    upstream=$(awk '$1 == "nameserver" && $2 != "127.0.0.1" { print $2 }' "${resolv_conf}" 2>/dev/null)

    if [ -z "${upstream}" ]; then
        upstream=$'1.1.1.1\n8.8.8.8'
    fi

    echo "${upstream}"
}

function write_resolv_conf {
    local nameservers="$1" search="${2:-}"

    {
        echo "${generated_by}"
        if [ -n "${search}" ]; then
            echo "search ${search}"
        fi
        while read -r nameserver; do
            echo "nameserver ${nameserver}"
        done <<< "${nameservers}"
    } > "${resolv_conf}.tmp"

    mv "${resolv_conf}.tmp" "${resolv_conf}"
}

# A node that no longer serves DNS (reconfigured from hub to bot, or from
# runtime to simulation) would otherwise keep resolving through a dnsmasq that
# is no longer running.
function restore_upstream_resolv_conf {
    if [ -w "${resolv_conf}" ] && grep -q "^${generated_by}$" "${resolv_conf}"; then
        echo "Restoring upstream nameservers in ${resolv_conf}"
        write_resolv_conf "$(upstream_nameservers)"
    fi
}

bot_id_min=$(jaia_bounds --bot_id --min)
bot_id_max=$(jaia_bounds --bot_id --max)
hub_id_min=$(jaia_bounds --hub_id --min)
hub_id_max=$(jaia_bounds --hub_id --max)
# the CloudHub is reachable over the CloudHub VPN rather than the fleet WLAN
cloudhub_id=$(jaia_bounds --cloudhub_id)

if [ "${type}" != "hub" ] || [ "${mode}" != "runtime" ] || [ "${node_id}" = "${cloudhub_id}" ]; then
    restore_upstream_resolv_conf
    exit 0
fi

if [ -z "${fleet}" ]; then
    echo "Failed to obtain fleet id - use '-f' or set debconf jaiabot-embedded/fleet_id" >&2
    exit 1
fi

domain=${jaia_network_dns_domain:-}
domain=${domain:-jaia}

# <ip> <name> [extra name]...: the fleet domain is written out for each name
# rather than left to dnsmasq's expand-hosts, which applies to hosts files only
# as a side effect of the DHCP server we don't run.
function host_record {
    local ip="$1" names="" name
    shift

    for name in "$@"; do
        names+=" ${name}.${domain} ${name}"
    done

    echo "${ip}${names}"
}

function wlan_host_record {
    local node_type="$1" id="$2" ip
    shift 2

    ip=$(jaia_ip --query_type addr --node_type "${node_type}" --node_id "${id}" \
                 --ip_net wlan --fleet_id "${fleet}")

    host_record "${ip}" "${node_type}${id}" "${node_type}${id}-fleet${fleet}" "$@"
}

echo ">>>>> Writing ${dns_hosts} ... "

{
    echo "${generated_by}"
    echo "# Fleet ${fleet} bot and hub names, from the addressing scheme of 'jaia ip'"

    for id in $(seq ${hub_id_min} ${hub_id_max}); do
        if [ "${id}" = "${cloudhub_id}" ]; then
            continue
        elif [ "${id}" = "${node_id}" ]; then
            # 'hub' is this hub, so that a client reaches the hub it asked
            wlan_host_record hub "${id}" hub
        else
            wlan_host_record hub "${id}"
        fi
    done

    for id in $(seq ${bot_id_min} ${bot_id_max}); do
        wlan_host_record bot "${id}"
    done

    cloudhub_ip=$(jaia_ip --query_type addr --node_type hub --node_id "${cloudhub_id}" \
                          --ip_net cloudhub_vpn --fleet_id "${fleet}" --ip_version ipv6)
    host_record "${cloudhub_ip}" "hub${cloudhub_id}" "hub${cloudhub_id}-fleet${fleet}" cloudhub
} > "${dns_hosts}.tmp"

mv "${dns_hosts}.tmp" "${dns_hosts}"

echo "<<<<< Writing ${dns_hosts} complete!"

echo ">>>>> Writing ${dnsmasq_conf} ... "

{
    echo "${generated_by}"
    # /etc/hosts maps this machine's own hostname to 127.0.0.1, which would be a
    # useless answer for every other node in the fleet
    echo "no-hosts"
    echo "addn-hosts=/etc/jaiabot/dns-hosts"
    echo "domain-needed"
    echo "bogus-priv"
    echo "local=/${domain}/"
    # bind-dynamic rather than bind-interfaces: the fleet wifi is usually not up
    # yet when this starts
    echo "bind-dynamic"
    echo "local-service"
    echo "listen-address=127.0.0.1"
    echo "interface=${jaia_network_wifi_iface:-wlan0}"
    # a static address on the wired interface means it, rather than wifi, is the
    # fleet network
    if [ -n "${jaia_network_eth_address:-}" ]; then
        echo "interface=${jaia_network_eth_iface:-eth0}"
    fi
    echo "no-resolv"
    while read -r nameserver; do
        echo "server=${nameserver}"
    done <<< "$(upstream_nameservers)"
} > "${dnsmasq_conf}.tmp"

mv "${dnsmasq_conf}.tmp" "${dnsmasq_conf}"

echo "<<<<< Writing ${dnsmasq_conf} complete!"

echo ">>>>> Writing ${resolv_conf} ... "

# The upstreams stay as fallbacks so that this machine still resolves public
# names if dnsmasq is stopped.
write_resolv_conf "$(printf '127.0.0.1\n%s' "$(upstream_nameservers)")" "${domain}"

echo "<<<<< Writing ${resolv_conf} complete!"
