deployment: sim_deployment
platforms:
  - name: hub
    interfaces:
      - application: goby_liaison
        file: jaiabot_liaison_interface.yml        
      - jaiabot_hub_manager_interface.yml
      - jaiabot_web_portal_interface.yml
      - jaiabot_metadata_interface.yml
      - @GOBY_INTERFACES_DIR@/goby_coroner_interface.yml
      - jaiabot_health_interface.yml
      - jaiabot_comms_manager_interface.yml
  - name: bot
    interfaces:
      - application: goby_moos_gateway
        file: jaiabot_moos_gateway_plugin_interface.yml
      - application: goby_moos_gateway
        file: @GOBY_INTERFACES_DIR@/goby_ivp_frontseat_moos_gateway_plugin_interface.yml
      - application: goby_liaison
        file: jaiabot_liaison_interface.yml
      - jaiabot_simulator_interface.yml
      - jaiabot_fusion_interface.yml
      - jaiabot_mission_manager_interface.yml
      - @GOBY_INTERFACES_DIR@/goby_gps_interface.yml
      - jaiabot_metadata_interface.yml
      - jaiabot_sensors_interface.yml
      - jaiabot_pid_control_interface.yml
      - jaiabot_engineering_interface.yml
      - @GOBY_INTERFACES_DIR@/goby_coroner_interface.yml
      - jaiabot_health_interface.yml
      - jaiabot_driver_camera_interface.yml
      - jaiabot_comms_manager_interface.yml
      - jaiabot_udp_gateway_interface.yml
