deployment: sim_deployment
platforms:
  - name: hub
    interfaces:
      - application: goby_liaison
        file: jaiabot_liaison_interface.yml        
      - @GOBY_INTERFACES_DIR@/goby_opencpn_interface_interface.yml
      - @GOBY_INTERFACES_DIR@/goby_geov_interface_interface.yml
      - jaiabot_hub_manager_interface.yml
      - jaiabot_web_portal_interface.yml
  - name: bot
    interfaces:
      - application: goby_moos_gateway
        file: jaiabot_moos_gateway_plugin_interface.yml
      - application: goby_moos_gateway
        file: @GOBY_INTERFACES_DIR@/goby_ivp_frontseat_moos_gateway_plugin_interface.yml
      - application: goby_liaison
        file: jaiabot_liaison_interface.yml
      - jaiabot_simulator_interface.yml
      - jaiabot_fusion_interface.yml
      - bluerobotics-pressure-sensor-driver_interface.yml
      - jaiabot_mission_manager_interface.yml
      - @GOBY_INTERFACES_DIR@/goby_gps_interface.yml
