DEBUG=true
# allocation ID for 52.38.143.8
# ELASTIC_IP_ALLOCATION_ID=eipalloc-03f3deeb10c48917c
IPV6_ADDRESS=2600:1f13:501:a401:44e2:99f1:4f72:cc31

ENABLE_TERMINATION_PROTECTION=true
SERVER_TYPE=packages
INDENTED_ROOT_PUBKEYS=$(sed 's/^/      /' ${SCRIPT_PATH}/../../../config/ssh/root_authorized_keys)
DO_ASSOCIATE_ELASTIC_IP=false
DISK_SIZE_GB=30
IPV6_ADDRESS=2600:1f13:501:a400:6091:99b:94fb:d50b

function create_security_group_rules()
{
    local SECURITY_GROUP_ID=$1
    # Set Up Security Group Rules
    run "" aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges='[{CidrIp=0.0.0.0/0}]',Ipv6Ranges='[{CidrIpv6=::/0}]'
    echo ">>>>>> Allowed SSH (port 22) on Security Group"

    run "" aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --ip-permissions IpProtocol=tcp,FromPort=80,ToPort=80,IpRanges='[{CidrIp=0.0.0.0/0}]',Ipv6Ranges='[{CidrIpv6=::/0}]'
    echo ">>>>>> Allowed HTTP (port 80) on Security Group"

    run "" aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --ip-permissions IpProtocol=tcp,FromPort=443,ToPort=443,IpRanges='[{CidrIp=0.0.0.0/0}]',Ipv6Ranges='[{CidrIpv6=::/0}]'
    echo ">>>>>> Allowed HTTP (port 443) on Security Group"


}
