---
- name: Jaiabot major upgrade
  hosts: localhost
  become: yes
  gather_facts: yes
  vars:
    - upgrade_dir_base: '/var/log/jaiabot/major_upgrade'
  
  tasks:
    - name: Create the upgrade base working directory
      file:
        path: '{{ upgrade_dir_base }}'
        state: directory
    
    - name: Find rootfs file
      find:
        paths: "/mnt/major_upgrade/"
        patterns: "*.rootfs.tar.gz"
      register: rootfs_files

    - name: Store first rootfs file in a variable
      set_fact:
        rootfs_filename: "{{ rootfs_files.files[0].path }}"
      when: rootfs_files.matched > 0

    - name: Display rootfs filename
      debug:
        msg: "rootfs file found: {{ rootfs_filename }}"
      when: rootfs_files.matched > 0

    - name: Set facts for upgrade script
      set_fact:
        upgrade_type: aws_ami
        upgrade_tmp_dir: '/tmp/dummy'
        upgrade_reuse_dir: '/tmp/dummy'
        upgrade_boot_dir: '/tmp/dummy'
        upgrade_dir: '{{ upgrade_dir_base }}'
        
    - name: Generate upgrade script
      template:
        src: templates/do-major-upgrade.sh.j2
        dest: '{{ upgrade_dir_base }}/do-major-upgrade.sh'
        mode: a=rwx

        # Actual script is run by packer as pivot_root breaks Ansible config
#    - name: Run upgrade script
#      shell: |
#        {{ upgrade_dir_base }}/do-major-upgrade.sh 2>&1 | tee {{ upgrade_dir_base }}/major_upgrade_final.log
