export enum JaiaSystemActions {
    INIT = "INIT",
    DATA_MODEL_POLLED = "DATA_MODEL_POLLED",
    ADD_MISSION = "ADD_MISSION",
    DELETE_MISSION = "DELETE_MISSION",
    DELETE_ALL_MISSIONS = "DELETE_ALL_MISSIONS",
    ASSIGN_BOT_TO_MISSION = "ASSIGN_BOT_TO_MISSION",
    AUTO_ASSIGN_BOTS_TO_MISSIONS = "AUTO_ASSIGN_BOTS_TO_MISSIONS",
}
