export enum JaiaSystemActions {
    DATA_MODEL_POLLED = "DATA_MODEL_POLLED",
    SYNC_REQUESTED = "SYNC_REQUESTED",
    ADD_MISSION = "ADD_MISSION",
    DELETE_MISSION = "DELETE_MISSION",
    DELETE_ALL_MISSIONS = "DELETE_ALL_MISSIONS",
    AUTO_ASSIGN = "AUTO_ASSIGN,",
}
