// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.21.12
// source: goby/middleware/protobuf/geographic.proto

/* eslint-disable */

export const protobufPackage = "goby.middleware.protobuf";

export interface LatLonPoint {
    lat?: number | undefined;
    lon?: number | undefined;
    depth?: number | undefined;
    altitude?: number | undefined;
}

/** protobuf contents of $GPWPL message */
export interface Waypoint {
    name?: string | undefined;
    location?: LatLonPoint | undefined;
}

/** protobuf contents of $GPRTE message */
export interface Route {
    name?: string | undefined;
    point?: Waypoint[] | undefined;
}
