export const UNASSIGNED_ID = -1;
export const NO_CONSTRAINT = -1;
export const DEFAULT_HUB_ID = 1;
export const DETAILS_DECIMALS = 2;
export const LAT_LON_DECIMALS = 5;
export const TEXT_OFFSET_RADIUS = 11;
export const NO_COMMS_STATUS_AGE = 30; // seconds
export const DATA_MODEL_POLL_TIME = 500; // milliseconds
export const TASK_PACKET_POLL_TIME = 1000; // milliseconds
export const INITAL_ZOOM_DURATION = 3000; // milliseconds
export const INITIAL_ZOOM = 15; // OpenLayers zoom level
export const SCROLL_DELAY = 30; // milliseconds
export const MIN_BATTERY_PERCENT = 20;
export const MAX_LAT = 90;
export const MIN_LAT = -90;
export const MAX_LON = 180;
export const MIN_LON = -180;
export const MERCATOR = "EPSG:3857";
export const DRIFT_INTENSITY_INTERVAL = 0.5; // meters per second
export const MAX_DRIFT_INTENSITY = 5;
export const MIN_SPEED = 0.5; // meters per second
export const MAX_SPEED = 3; // meters per second
export const HUB_COMMS_INNER_RADIUS = 250; // meters
export const HUB_COMMS_OUTER_RADIUS = 500; // meters
export const MDI_BUTTON_SIZE = 1.3;
export const KILOMETER_FACTOR = 1000;
