export const UNASSIGNED_ID = -1;
export const CLOUD_HUB_ID = 30;
export const NO_CONSTRAINT = -1;
export const DEFAULT_LANES = 5;
export const DETAILS_DECIMALS = 2;
export const LAT_LON_DECIMALS = 5;
export const TEXT_OFFSET_RADIUS = 11;
export const HUB_TEXT_OFFSET_RADIUS = 10;
export const NO_COMMS_STATUS_AGE = 30; // seconds
export const IRIDIUM_NO_COMMS_STATUS_AGE = 180; // seconds (3 minutes)
export const DATA_MODEL_POLL_TIME = 500; // milliseconds
export const TASK_PACKET_POLL_TIME = 1000; // milliseconds
export const BATTERY_PREDICTION_POLL_TIME = 1000; // milliseconds
export const BATTERY_PREDICTION_REFRESH_DEBOUNCE_MS = 500; // milliseconds
export const METADATA_POLL_TIME = 10_000; // milliseconds
export const INTERNET_POLL_TIME = 15_000; // millisecondss
export const GITHUB_POLL_TIME = 120_000; // milliseconds
export const OSM_MAX_ZOOM = 19;
export const ARC_GIS_MAX_ZOOM = 19;
export const SCROLL_DELAY = 30; // milliseconds
export const MIN_BATTERY_PERCENT = 20;
export const BOTTOM_DIVE_DEPTH_PRIOR_M = 10;
export const MAX_LAT = 84; // Set by MGRS library
export const MIN_LAT = -80; // Set by MGRS library
export const MAX_LON = 180;
export const MIN_LON = -180;
export const MERCATOR = "EPSG:3857";
export const EQUIRECTANGULAR = "EPSG:4326";
export const DRIFT_INTENSITY_INTERVAL = 0.5; // meters per second
export const MAX_DRIFT_INTENSITY = 5;
export const MIN_SPEED = 0.5; // meters per second
export const MAX_SPEED = 3; // meters per second
export const DEFAULT_SPEED = 2; // meters per second
export const HUB_COMMS_INNER_RADIUS = 250; // meters
export const HUB_COMMS_OUTER_RADIUS = 500; // meters
export const MDI_BUTTON_SIZE = 1.3;
export const KILOMETER_FACTOR = 1000;
export const MAX_HISTORY = 15;
export const MISSION_ENDPOINTS = 2;
export const DEPTH_MAP_3D_NAME = "depth-map-3d";
export const MAX_WAYPOINTS = 80;
export const TASK_ZERO_LOWER_BOUND = 0;
export const TASK_MAX_DEPTH_CONSTRAINT = 50;
export const TASK_MAX_HOLD_TIME_CONSTRAINT = 80;
export const TASK_MAX_HEADING_CONSTRAINT = 360;
export const TASK_MIN_SPEED_CONSTRAINT = 1;
export const TASK_MAX_SPEED_CONSTRAINT = 3;
export const JCC_CONTAINER = "jcc";
export const MAP_FEATURE_HIT_TOLERANCE = 15; // px
export const DEFAULT_MISSION_SET_NAME = "";
export const MGRS_PLACEHOLDER = "N/A";
export const METERS_PER_DEG = 111320; // metres per degree of latitude (approximate, good to 0.1% at all latitudes)
