DEBUG=true
# allocation ID for 44.233.97.88
ELASTIC_IP_ALLOCATION_ID=eipalloc-0b2441c45eff7c158
ENABLE_TERMINATION_PROTECTION=false
SERVER_TYPE=iridium
REPO=continuous
INDENTED_ROOT_PUBKEYS=$(sed 's/^/      /' ${SCRIPT_PATH}/../../../config/ssh/root_authorized_keys)

function create_security_group_rules()
{
    local SECURITY_GROUP_ID=$1
    # Set Up Security Group Rules
    run "" aws ec2 authorize-security-group-ingress --group-id $SECURITY_GROUP_ID --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges='[{CidrIp=0.0.0.0/0}]',Ipv6Ranges='[{CidrIpv6=::/0}]'
    echo ">>>>>> Allowed SSH (port 22) on Security Group"

    IRIDIUM_CIDR="12.47.179.0/24"
    run "" aws ec2 authorize-security-group-ingress \
        --group-id $SECURITY_GROUP_ID \
        --protocol tcp \
        --port 11800-12799 \
        --cidr ${IRIDIUM_CIDR}

    echo ">>>>>> Allowed Iridium MO SBD (our ports 11800-12799) on Security Group"

    ROCKBLOCK_MO_IP="109.74.196.135 212.71.235.32"
    for ip in $ROCKBLOCK_MO_IP; do
        run "" aws ec2 authorize-security-group-ingress \
            --group-id "$SECURITY_GROUP_ID" \
            --protocol tcp \
            --port 12800-13799 \
            --cidr "$ip/32"
    done
    echo ">>>>>> Allowed RockBLOCK MO HTTP (our ports 12800-13799) on Security Group"

}
