DEBUG=true
# allocation ID for 44.233.97.88
ELASTIC_IP_ALLOCATION_ID=eipalloc-0b2441c45eff7c158
ENABLE_TERMINATION_PROTECTION=false
SERVER_TYPE=iridium
REPO=continuous
INDENTED_ROOT_PUBKEYS=$(sed 's/^/      /' ${SCRIPT_PATH}/../../../config/ssh/root_authorized_keys)
