// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.21.12
// source: jaiabot/messages/bounds.proto

/* eslint-disable */

export const protobufPackage = "jaiabot.protobuf";

export interface SurfaceBounds {
    upper?: number | undefined;
    lower?: number | undefined;
    center?: number | undefined;
}

export interface MotorBounds {
    forwardStart?: number | undefined;
    reverseStart?: number | undefined;
    max_reverse?: number | undefined;
    throttle_zero_net_buoyancy?: number | undefined;
    throttle_dive?: number | undefined;
    throttle_ascent?: number | undefined;
}

export interface Bounds {
    strb?: SurfaceBounds | undefined;
    port?: SurfaceBounds | undefined;
    rudder?: SurfaceBounds | undefined;
    motor?: MotorBounds | undefined;
}
