// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.21.12
// source: jaiabot/messages/hub.proto

/* eslint-disable */
import type { HealthState } from "../../goby/middleware/protobuf/coroner";
import type { GeographicCoordinate } from "./geographic_coordinate";
import type { Error, LinuxHardwareStatus, Warning } from "./health";
import type { Link } from "./link";

export const protobufPackage = "jaiabot.protobuf";

export interface HubStatus {
    hub_id?: number | undefined;
    fleet_id?: number | undefined;
    time?: string | undefined;
    health_state?: HealthState | undefined;
    error?: Error[] | undefined;
    warning?: Warning[] | undefined;
    location?: GeographicCoordinate | undefined;
    bot_ids_in_radio_file?: number[] | undefined;
    linux_hardware_status?: LinuxHardwareStatus | undefined;
    bot_offload?: HubStatus_BotOffloadData | undefined;
    received_time?: string | undefined;
    known_bot?: HubStatus_KnownBot[] | undefined;
    active_link?: Link[] | undefined;
}

export interface HubStatus_BotOffloadData {
    bot_id?: number | undefined;
    data_offload_percentage?: number | undefined;
    offload_succeeded?: boolean | undefined;
    bots_pending?: number[] | undefined;
}

export interface HubStatus_KnownBot {
    id?: number | undefined;
    last_status_time?: string | undefined;
}
