// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.21.12
// source: jaiabot/messages/imu.proto

/* eslint-disable */
import type { MissionState } from "./mission";

export const protobufPackage = "jaiabot.protobuf";

export enum IMUCalibrationState {
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETE = "COMPLETE",
}

export interface IMUCommand {
    type?: IMUCommand_IMUCommandType | undefined;
    /** / Sample rate for data collection in Hz */
    sample_rate?: number | undefined;
}

export enum IMUCommand_IMUCommandType {
    CONFIGURE = "CONFIGURE",
    START_WAVE_HEIGHT_SAMPLING = "START_WAVE_HEIGHT_SAMPLING",
    STOP_WAVE_HEIGHT_SAMPLING = "STOP_WAVE_HEIGHT_SAMPLING",
    START_BOTTOM_TYPE_SAMPLING = "START_BOTTOM_TYPE_SAMPLING",
    STOP_BOTTOM_TYPE_SAMPLING = "STOP_BOTTOM_TYPE_SAMPLING",
    START_CALIBRATION = "START_CALIBRATION",
}

export interface IMUData {
    euler_angles?: IMUData_EulerAngles | undefined;
    linear_acceleration?: IMUData_Acceleration | undefined;
    gravity?: IMUData_Acceleration | undefined;
    accuracies?: IMUData_Accuracies | undefined;
    calibration_state?: IMUCalibrationState | undefined;
    bot_rolled_over?: boolean | undefined;
    significant_wave_height?: number | undefined;
    /** For bottom characterization */
    max_acceleration?: number | undefined;
    angular_velocity?: IMUData_AngularVelocity | undefined;
    quaternion?: IMUData_Quaternion | undefined;
    imu_type?: string | undefined;
    acceleration?: IMUData_Acceleration | undefined;
    magnetic_field?: IMUData_MagneticField | undefined;
    linear_acceleration_world?: IMUData_AccelerationWorld | undefined;
}

export interface IMUData_EulerAngles {
    heading?: number | undefined;
    pitch?: number | undefined;
    roll?: number | undefined;
}

export interface IMUData_Acceleration {
    x?: number | undefined;
    y?: number | undefined;
    z?: number | undefined;
}

export interface IMUData_Accuracies {
    accelerometer?: number | undefined;
    gyroscope?: number | undefined;
    magnetometer?: number | undefined;
}

export interface IMUData_AngularVelocity {
    x?: number | undefined;
    y?: number | undefined;
    z?: number | undefined;
}

export interface IMUData_Quaternion {
    w?: number | undefined;
    x?: number | undefined;
    y?: number | undefined;
    z?: number | undefined;
}

export interface IMUData_MagneticField {
    x?: number | undefined;
    y?: number | undefined;
    z?: number | undefined;
}

export interface IMUData_AccelerationWorld {
    north?: number | undefined;
    east?: number | undefined;
    down?: number | undefined;
}

export interface IMUIssue {
    solution?: IMUIssue_SolutionType | undefined;
    type?: IMUIssue_IssueType | undefined;
    mission_state?: MissionState | undefined;
    imu_heading_course_max_diff?: number | undefined;
    heading?: number | undefined;
    desired_heading?: number | undefined;
    course_over_ground?: number | undefined;
    heading_course_difference?: number | undefined;
    pitch?: number | undefined;
    speed_over_ground?: number | undefined;
    desired_speed?: number | undefined;
}

export enum IMUIssue_SolutionType {
    STOP_BOT = "STOP_BOT",
    USE_COG = "USE_COG",
    USE_CORRECTION = "USE_CORRECTION",
    RESTART_BOT = "RESTART_BOT",
    REBOOT_BOT = "REBOOT_BOT",
    REPORT_IMU = "REPORT_IMU",
    RESTART_IMU_PY = "RESTART_IMU_PY",
    REBOOT_BNO085_IMU = "REBOOT_BNO085_IMU",
    REBOOT_BNO085_IMU_AND_RESTART_IMU_PY = "REBOOT_BNO085_IMU_AND_RESTART_IMU_PY",
}

export enum IMUIssue_IssueType {
    HEADING_COURSE_DIFFERENCE_TOO_LARGE = "HEADING_COURSE_DIFFERENCE_TOO_LARGE",
}
