// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.21.12
// source: jaiabot/messages/link.proto

/* eslint-disable */

export const protobufPackage = "jaiabot.protobuf";

/** these enum values MUST match those in config/gen/common/comms.py 'subnet_index' */
export enum Link {
    LINK_UNKNOWN = "LINK_UNKNOWN",
    LINK_XBEE = "LINK_XBEE",
    LINK_WIFI = "LINK_WIFI",
    LINK_IRIDIUM = "LINK_IRIDIUM",
    LINK_HUB2HUB = "LINK_HUB2HUB",
}
