// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.21.12
// source: jaiabot/messages/pam.proto

/* eslint-disable */

export const protobufPackage = "jaiabot.protobuf";

export enum PamState {
    BOOTING = "BOOTING",
    OCTOSPI = "OCTOSPI",
    SD_INIT = "SD_INIT",
    SD_MOUNT = "SD_MOUNT",
    SD_CREATE = "SD_CREATE",
    PSSI_EN = "PSSI_EN",
    READY = "READY",
    START = "START",
    STOP = "STOP",
    RUNNING = "RUNNING",
}

export interface PamCommand {
    type?: PamCommand_PamCommandType | undefined;
}

export enum PamCommand_PamCommandType {
    CMD_START = "CMD_START",
    CMD_STOP = "CMD_STOP",
    CMD_STORAGE = "CMD_STORAGE",
    CMD_ACK = "CMD_ACK",
    CMD_STATUS = "CMD_STATUS",
    CMD_CH = "CMD_CH",
    CMD_FREQ = "CMD_FREQ",
    CMD_TIME = "CMD_TIME",
    CMD_VER = "CMD_VER",
    CMD_HELP = "CMD_HELP",
}

export interface PamData {
    pam_state?: PamState | undefined;
}

export interface PamIssue {
    solution?: PamIssue_SolutionType | undefined;
}

export enum PamIssue_SolutionType {
    REPORT_PAM = "REPORT_PAM",
    RESTART_PAM_PY = "RESTART_PAM_PY",
    REBOOT_PAM_IMU_AND_RESTART_PAM_PY = "REBOOT_PAM_IMU_AND_RESTART_PAM_PY",
}
