// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v3.21.12
// source: jaiabot/messages/rest_api.proto

/* eslint-disable */
import type { HubStatus } from "./hub";
import type { BotStatus, Command, CommandForHub, TaskPacket } from "./jaia_dccl";
import type { DeviceMetadata } from "./metadata";
import type { MissionSummary } from "./mission";

export const protobufPackage = "jaiabot.protobuf";

export enum APIErrorCode {
    /** API_ERROR__UNSUPPORTED_API_VERSION - REST API URL errors */
    API_ERROR__UNSUPPORTED_API_VERSION = "API_ERROR__UNSUPPORTED_API_VERSION",
    API_ERROR__INVALID_ACTION = "API_ERROR__INVALID_ACTION",
    API_ERROR__TARGETS_STRING_MALFORMATTED = "API_ERROR__TARGETS_STRING_MALFORMATTED",
    API_ERROR__ACTION_REQUIRES_JSON_POST_DATA = "API_ERROR__ACTION_REQUIRES_JSON_POST_DATA",
    API_ERROR__INVALID_TARGET = "API_ERROR__INVALID_TARGET",
    /** API_ERROR__COULD_NOT_PARSE_API_REQUEST_JSON - Parse errors */
    API_ERROR__COULD_NOT_PARSE_API_REQUEST_JSON = "API_ERROR__COULD_NOT_PARSE_API_REQUEST_JSON",
    /** API_ERROR__REQUEST_NOT_INITIALIZED - Missing fields */
    API_ERROR__REQUEST_NOT_INITIALIZED = "API_ERROR__REQUEST_NOT_INITIALIZED",
    API_ERROR__NO_ACTION_SPECIFIED = "API_ERROR__NO_ACTION_SPECIFIED",
    API_ERROR__INVALID_TYPE = "API_ERROR__INVALID_TYPE",
    /** API_ERROR__NOT_IMPLEMENTED - Unimplemented */
    API_ERROR__NOT_IMPLEMENTED = "API_ERROR__NOT_IMPLEMENTED",
}

export interface TaskPacketQuery {
    start_time?: string | undefined;
    end_time?: string | undefined;
    mission_name?: string[] | undefined;
    included_only?: boolean | undefined;
    format?: TaskPacketQuery_Format | undefined;
}

export enum TaskPacketQuery_Format {
    JSON = "JSON",
    KMZ = "KMZ",
    CSV = "CSV",
    GEOJSON_CONTOURS = "GEOJSON_CONTOURS",
}

export interface TaskPacketQueryResults {
    packets?: TaskPacket[] | undefined;
}

export interface MissionQuery {
    start_time?: string | undefined;
    end_time?: string | undefined;
}

export interface MissionQueryResults {
    mission_summaries?: MissionSummary[] | undefined;
}

export interface CommandResult {
    command_sent?: boolean | undefined;
}

export interface APIError {
    code?: APIErrorCode | undefined;
    details?: string | undefined;
}

export interface APIRequest {
    target?: APIRequest_Nodes | undefined;
    api_key?: string | undefined;
    status?: boolean | undefined;
    metadata?: boolean | undefined;
    task_packets?: TaskPacketQuery | undefined;
    missions?: MissionQuery | undefined;
    command?: Command | undefined;
    command_for_hub?: CommandForHub | undefined;
}

export interface APIRequest_Nodes {
    hubs?: number[] | undefined;
    bots?: number[] | undefined;
    all?: boolean | undefined;
}

export interface APIResponse {
    target?: APIResponse_Nodes | undefined;
    error?: APIError | undefined;
    status?: APIResponse_Statuses | undefined;
    metadata?: APIResponse_Metadatas | undefined;
    task_packets?: TaskPacketQueryResults | undefined;
    missions?: MissionQueryResults | undefined;
    command_result?: CommandResult | undefined;
    /** copy of original request */
    request?: APIRequest | undefined;
}

export interface APIResponse_Nodes {
    hubs?: number[] | undefined;
    bots?: number[] | undefined;
}

export interface APIResponse_Statuses {
    bots?: BotStatus[] | undefined;
    hubs?: HubStatus[] | undefined;
}

export interface APIResponse_Metadatas {
    hubs?: DeviceMetadata[] | undefined;
}

export interface APIConfig {
    streaming_endpoint?: APIConfig_StreamingEndpoint[] | undefined;
    flask_bind_port?: number | undefined;
    /** set true if no API key is required */
    no_key_required?: boolean | undefined;
    key?: APIConfig_APIKey[] | undefined;
}

export interface APIConfig_StreamingEndpoint {
    hub_id?: number | undefined;
    hostname?: string | undefined;
    port?: number | undefined;
}

export interface APIConfig_APIKey {
    private_key?: string | undefined;
    permission?: APIConfig_APIKey_Permission[] | undefined;
}

export enum APIConfig_APIKey_Permission {
    ALL = "ALL",
    READ = "READ",
    WRITE = "WRITE",
    STATUS = "STATUS",
    METADATA = "METADATA",
    TASK_PACKETS = "TASK_PACKETS",
    MISSIONS = "MISSIONS",
    COMMAND = "COMMAND",
    COMMAND_FOR_HUB = "COMMAND_FOR_HUB",
}
