# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goby/middleware/protobuf/coroner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goby/middleware/protobuf/coroner.proto',
  package='goby.middleware.protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n&goby/middleware/protobuf/coroner.proto\x12\x18goby.middleware.protobuf\x1a\x1c\x64\x63\x63l/option_extensions.proto\"\x0f\n\rHealthRequest\"\xa0\x02\n\x0cThreadHealth\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x13\n\tthread_id\x18\x02 \x01(\x05H\x00\x12\x19\n\x0fthread_id_apple\x18\x04 \x01(\x04H\x00\x12\x0b\n\x03uid\x18\x03 \x01(\x05\x12\x34\n\x05state\x18\n \x02(\x0e\x32%.goby.middleware.protobuf.HealthState\x12\x35\n\x05\x63hild\x18\x0b \x03(\x0b\x32&.goby.middleware.protobuf.ThreadHealth\x12.\n\x05\x65rror\x18\x14 \x01(\x0e\x32\x1f.goby.middleware.protobuf.Error\x12\x15\n\rerror_message\x18\x15 \x01(\t*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\x42\x06\n\x04t_id\"k\n\rProcessHealth\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03pid\x18\x02 \x01(\r\x12\x34\n\x04main\x18\n \x02(\x0b\x32&.goby.middleware.protobuf.ThreadHealth*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\"\xc6\x01\n\rVehicleHealth\x12\x1e\n\x04time\x18\x01 \x02(\x04\x42\x10\xa2?\r\xf2\x01\n\n\x01T2\x05micro\x12\x10\n\x08platform\x18\x02 \x02(\t\x12\x34\n\x05state\x18\n \x02(\x0e\x32%.goby.middleware.protobuf.HealthState\x12\x38\n\x07process\x18\x0b \x03(\x0b\x32\'.goby.middleware.protobuf.ProcessHealth*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02:\x08\xa2?\x05\xf2\x01\x02si*G\n\x0bHealthState\x12\x0e\n\nHEALTH__OK\x10\x01\x12\x14\n\x10HEALTH__DEGRADED\x10\x02\x12\x12\n\x0eHEALTH__FAILED\x10\x03*B\n\x05\x45rror\x12\x17\n\x13\x45RROR__PROCESS_DIED\x10\x01\x12 \n\x1c\x45RROR__THREAD_NOT_RESPONDING\x10\x64')
  ,
  dependencies=[dccl_dot_option__extensions__pb2.DESCRIPTOR,])

_HEALTHSTATE = _descriptor.EnumDescriptor(
  name='HealthState',
  full_name='goby.middleware.protobuf.HealthState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HEALTH__OK', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEALTH__DEGRADED', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEALTH__FAILED', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=716,
  serialized_end=787,
)
_sym_db.RegisterEnumDescriptor(_HEALTHSTATE)

HealthState = enum_type_wrapper.EnumTypeWrapper(_HEALTHSTATE)
_ERROR = _descriptor.EnumDescriptor(
  name='Error',
  full_name='goby.middleware.protobuf.Error',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR__PROCESS_DIED', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR__THREAD_NOT_RESPONDING', index=1, number=100,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=789,
  serialized_end=855,
)
_sym_db.RegisterEnumDescriptor(_ERROR)

Error = enum_type_wrapper.EnumTypeWrapper(_ERROR)
HEALTH__OK = 1
HEALTH__DEGRADED = 2
HEALTH__FAILED = 3
ERROR__PROCESS_DIED = 1
ERROR__THREAD_NOT_RESPONDING = 100



_HEALTHREQUEST = _descriptor.Descriptor(
  name='HealthRequest',
  full_name='goby.middleware.protobuf.HealthRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=113,
)


_THREADHEALTH = _descriptor.Descriptor(
  name='ThreadHealth',
  full_name='goby.middleware.protobuf.ThreadHealth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='goby.middleware.protobuf.ThreadHealth.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread_id', full_name='goby.middleware.protobuf.ThreadHealth.thread_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='thread_id_apple', full_name='goby.middleware.protobuf.ThreadHealth.thread_id_apple', index=2,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='goby.middleware.protobuf.ThreadHealth.uid', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='goby.middleware.protobuf.ThreadHealth.state', index=4,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='child', full_name='goby.middleware.protobuf.ThreadHealth.child', index=5,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='goby.middleware.protobuf.ThreadHealth.error', index=6,
      number=20, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='goby.middleware.protobuf.ThreadHealth.error_message', index=7,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000, 536870912), ],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='t_id', full_name='goby.middleware.protobuf.ThreadHealth.t_id',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=116,
  serialized_end=404,
)


_PROCESSHEALTH = _descriptor.Descriptor(
  name='ProcessHealth',
  full_name='goby.middleware.protobuf.ProcessHealth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='goby.middleware.protobuf.ProcessHealth.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pid', full_name='goby.middleware.protobuf.ProcessHealth.pid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='main', full_name='goby.middleware.protobuf.ProcessHealth.main', index=2,
      number=10, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000, 536870912), ],
  oneofs=[
  ],
  serialized_start=406,
  serialized_end=513,
)


_VEHICLEHEALTH = _descriptor.Descriptor(
  name='VehicleHealth',
  full_name='goby.middleware.protobuf.VehicleHealth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='goby.middleware.protobuf.VehicleHealth.time', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\242?\r\362\001\n\n\001T2\005micro'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='goby.middleware.protobuf.VehicleHealth.platform', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='goby.middleware.protobuf.VehicleHealth.state', index=2,
      number=10, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process', full_name='goby.middleware.protobuf.VehicleHealth.process', index=3,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('\242?\005\362\001\002si'),
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000, 536870912), ],
  oneofs=[
  ],
  serialized_start=516,
  serialized_end=714,
)

_THREADHEALTH.fields_by_name['state'].enum_type = _HEALTHSTATE
_THREADHEALTH.fields_by_name['child'].message_type = _THREADHEALTH
_THREADHEALTH.fields_by_name['error'].enum_type = _ERROR
_THREADHEALTH.oneofs_by_name['t_id'].fields.append(
  _THREADHEALTH.fields_by_name['thread_id'])
_THREADHEALTH.fields_by_name['thread_id'].containing_oneof = _THREADHEALTH.oneofs_by_name['t_id']
_THREADHEALTH.oneofs_by_name['t_id'].fields.append(
  _THREADHEALTH.fields_by_name['thread_id_apple'])
_THREADHEALTH.fields_by_name['thread_id_apple'].containing_oneof = _THREADHEALTH.oneofs_by_name['t_id']
_PROCESSHEALTH.fields_by_name['main'].message_type = _THREADHEALTH
_VEHICLEHEALTH.fields_by_name['state'].enum_type = _HEALTHSTATE
_VEHICLEHEALTH.fields_by_name['process'].message_type = _PROCESSHEALTH
DESCRIPTOR.message_types_by_name['HealthRequest'] = _HEALTHREQUEST
DESCRIPTOR.message_types_by_name['ThreadHealth'] = _THREADHEALTH
DESCRIPTOR.message_types_by_name['ProcessHealth'] = _PROCESSHEALTH
DESCRIPTOR.message_types_by_name['VehicleHealth'] = _VEHICLEHEALTH
DESCRIPTOR.enum_types_by_name['HealthState'] = _HEALTHSTATE
DESCRIPTOR.enum_types_by_name['Error'] = _ERROR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), dict(
  DESCRIPTOR = _HEALTHREQUEST,
  __module__ = 'goby.middleware.protobuf.coroner_pb2'
  # @@protoc_insertion_point(class_scope:goby.middleware.protobuf.HealthRequest)
  ))
_sym_db.RegisterMessage(HealthRequest)

ThreadHealth = _reflection.GeneratedProtocolMessageType('ThreadHealth', (_message.Message,), dict(
  DESCRIPTOR = _THREADHEALTH,
  __module__ = 'goby.middleware.protobuf.coroner_pb2'
  # @@protoc_insertion_point(class_scope:goby.middleware.protobuf.ThreadHealth)
  ))
_sym_db.RegisterMessage(ThreadHealth)

ProcessHealth = _reflection.GeneratedProtocolMessageType('ProcessHealth', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSHEALTH,
  __module__ = 'goby.middleware.protobuf.coroner_pb2'
  # @@protoc_insertion_point(class_scope:goby.middleware.protobuf.ProcessHealth)
  ))
_sym_db.RegisterMessage(ProcessHealth)

VehicleHealth = _reflection.GeneratedProtocolMessageType('VehicleHealth', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLEHEALTH,
  __module__ = 'goby.middleware.protobuf.coroner_pb2'
  # @@protoc_insertion_point(class_scope:goby.middleware.protobuf.VehicleHealth)
  ))
_sym_db.RegisterMessage(VehicleHealth)


_VEHICLEHEALTH.fields_by_name['time']._options = None
_VEHICLEHEALTH._options = None
# @@protoc_insertion_point(module_scope)
