# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: goby/middleware/protobuf/intermodule.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2
from goby.protobuf import option_extensions_pb2 as goby_dot_protobuf_dot_option__extensions__pb2
from goby.middleware.protobuf import serializer_transporter_pb2 as goby_dot_middleware_dot_protobuf_dot_serializer__transporter__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='goby/middleware/protobuf/intermodule.proto',
  package='goby.middleware.intermodule.protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n*goby/middleware/protobuf/intermodule.proto\x12$goby.middleware.intermodule.protobuf\x1a\x1c\x64\x63\x63l/option_extensions.proto\x1a%goby/protobuf/option_extensions.proto\x1a\x35goby/middleware/protobuf/serializer_transporter.proto\"\xe5\x01\n\x0cSubscription\x12\n\n\x02id\x18\x01 \x02(\t\x12?\n\x03key\x18\x02 \x01(\x0b\x32\x32.goby.middleware.protobuf.SerializerTransporterKey\x12I\n\x06\x61\x63tion\x18\x05 \x02(\x0e\x32\x39.goby.middleware.intermodule.protobuf.Subscription.Action\"=\n\x06\x41\x63tion\x12\r\n\tSUBSCRIBE\x10\x01\x12\x0f\n\x0bUNSUBSCRIBE\x10\x02\x12\x13\n\x0fUNSUBSCRIBE_ALL\x10\x03')
  ,
  dependencies=[dccl_dot_option__extensions__pb2.DESCRIPTOR,goby_dot_protobuf_dot_option__extensions__pb2.DESCRIPTOR,goby_dot_middleware_dot_protobuf_dot_serializer__transporter__pb2.DESCRIPTOR,])



_SUBSCRIPTION_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='goby.middleware.intermodule.protobuf.Subscription.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUBSCRIBE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUBSCRIBE', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSUBSCRIBE_ALL', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=377,
  serialized_end=438,
)
_sym_db.RegisterEnumDescriptor(_SUBSCRIPTION_ACTION)


_SUBSCRIPTION = _descriptor.Descriptor(
  name='Subscription',
  full_name='goby.middleware.intermodule.protobuf.Subscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='goby.middleware.intermodule.protobuf.Subscription.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='goby.middleware.intermodule.protobuf.Subscription.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='goby.middleware.intermodule.protobuf.Subscription.action', index=2,
      number=5, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SUBSCRIPTION_ACTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=438,
)

_SUBSCRIPTION.fields_by_name['key'].message_type = goby_dot_middleware_dot_protobuf_dot_serializer__transporter__pb2._SERIALIZERTRANSPORTERKEY
_SUBSCRIPTION.fields_by_name['action'].enum_type = _SUBSCRIPTION_ACTION
_SUBSCRIPTION_ACTION.containing_type = _SUBSCRIPTION
DESCRIPTOR.message_types_by_name['Subscription'] = _SUBSCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Subscription = _reflection.GeneratedProtocolMessageType('Subscription', (_message.Message,), dict(
  DESCRIPTOR = _SUBSCRIPTION,
  __module__ = 'goby.middleware.protobuf.intermodule_pb2'
  # @@protoc_insertion_point(class_scope:goby.middleware.intermodule.protobuf.Subscription)
  ))
_sym_db.RegisterMessage(Subscription)


# @@protoc_insertion_point(module_scope)
