# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jaiabot/messages/moos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dccl import option_extensions_pb2 as dccl_dot_option__extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='jaiabot/messages/moos.proto',
  package='jaiabot.protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1bjaiabot/messages/moos.proto\x12\x10jaiabot.protobuf\x1a\x1c\x64\x63\x63l/option_extensions.proto\"\xa2\x02\n\x0bMOOSMessage\x12\x30\n\x04type\x18\x01 \x02(\x0e\x32\".jaiabot.protobuf.MOOSMessage.Type\x12\x0b\n\x03key\x18\x02 \x02(\t\x12\x10\n\x06svalue\x18\x03 \x01(\tH\x00\x12\x10\n\x06\x64value\x18\x04 \x01(\x01H\x00\x12\x10\n\x06\x62value\x18\x05 \x01(\x0cH\x00\x12\x10\n\x08unixtime\x18\x06 \x02(\x01\x12\n\n\x02id\x18\x07 \x02(\x05\x12\x0e\n\x06source\x18\x08 \x02(\t\x12\x12\n\nsource_aux\x18\t \x01(\t\x12\x11\n\tcommunity\x18\n \x02(\t\"@\n\x04Type\x12\x0f\n\x0bTYPE_DOUBLE\x10\x44\x12\x0f\n\x0bTYPE_STRING\x10S\x12\x16\n\x12TYPE_BINARY_STRING\x10\x42\x42\x07\n\x05value')
  ,
  dependencies=[dccl_dot_option__extensions__pb2.DESCRIPTOR,])



_MOOSMESSAGE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='jaiabot.protobuf.MOOSMessage.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TYPE_DOUBLE', index=0, number=68,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_STRING', index=1, number=83,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TYPE_BINARY_STRING', index=2, number=66,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=297,
  serialized_end=361,
)
_sym_db.RegisterEnumDescriptor(_MOOSMESSAGE_TYPE)


_MOOSMESSAGE = _descriptor.Descriptor(
  name='MOOSMessage',
  full_name='jaiabot.protobuf.MOOSMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='jaiabot.protobuf.MOOSMessage.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=68,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='jaiabot.protobuf.MOOSMessage.key', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='svalue', full_name='jaiabot.protobuf.MOOSMessage.svalue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dvalue', full_name='jaiabot.protobuf.MOOSMessage.dvalue', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bvalue', full_name='jaiabot.protobuf.MOOSMessage.bvalue', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unixtime', full_name='jaiabot.protobuf.MOOSMessage.unixtime', index=5,
      number=6, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='jaiabot.protobuf.MOOSMessage.id', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='jaiabot.protobuf.MOOSMessage.source', index=7,
      number=8, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_aux', full_name='jaiabot.protobuf.MOOSMessage.source_aux', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='community', full_name='jaiabot.protobuf.MOOSMessage.community', index=9,
      number=10, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MOOSMESSAGE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='jaiabot.protobuf.MOOSMessage.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=80,
  serialized_end=370,
)

_MOOSMESSAGE.fields_by_name['type'].enum_type = _MOOSMESSAGE_TYPE
_MOOSMESSAGE_TYPE.containing_type = _MOOSMESSAGE
_MOOSMESSAGE.oneofs_by_name['value'].fields.append(
  _MOOSMESSAGE.fields_by_name['svalue'])
_MOOSMESSAGE.fields_by_name['svalue'].containing_oneof = _MOOSMESSAGE.oneofs_by_name['value']
_MOOSMESSAGE.oneofs_by_name['value'].fields.append(
  _MOOSMESSAGE.fields_by_name['dvalue'])
_MOOSMESSAGE.fields_by_name['dvalue'].containing_oneof = _MOOSMESSAGE.oneofs_by_name['value']
_MOOSMESSAGE.oneofs_by_name['value'].fields.append(
  _MOOSMESSAGE.fields_by_name['bvalue'])
_MOOSMESSAGE.fields_by_name['bvalue'].containing_oneof = _MOOSMESSAGE.oneofs_by_name['value']
DESCRIPTOR.message_types_by_name['MOOSMessage'] = _MOOSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MOOSMessage = _reflection.GeneratedProtocolMessageType('MOOSMessage', (_message.Message,), dict(
  DESCRIPTOR = _MOOSMESSAGE,
  __module__ = 'jaiabot.messages.moos_pb2'
  # @@protoc_insertion_point(class_scope:jaiabot.protobuf.MOOSMessage)
  ))
_sym_db.RegisterMessage(MOOSMessage)


# @@protoc_insertion_point(module_scope)
